[클린코드 2기 표후동] 자판기 미션 STEP1
next-step/js-vending-machine pull request #33
Opened 2022-04-20 10:09 UTC by hdpyo

안녕하세요, 리뷰어님.
미션 진행이 많이 늦었네요... 😢 
STEP1 진행한만큼이라도 먼저 리뷰 요청드립니다.

---

## 요구사항

- [x] 상품 추가 입력 폼에 상품명, 금액, 수량을 차례로 입력한다.
- [x] 상품명, 금액, 수량은 공백이 불가능하다.
- [x] 상품의 최소 수량은 1개여야 한다.
- [x] 상품의 최소 가격은 100원이며, 10원으로 나누어 떨어져야 한다.
- [x] 같은 상품명의 데이터를 추가하면 기존의 상품에 해당하는 데이터는 새로운 상품으로 대체된다.
- [x] 사용자는 추가한 상품을 확인할 수 있다.
- [x] 상품의 이름, 가격, 수량 순으로 상품 목록이 보여진다.
- [ ] 상품 목록은 탭을 이동하여도 기존의 상품 목록이 유지되어야 한다.

---

### 구현할 때 중점을 둔 내용 & 기타
- 최대한 TDD 를 실천해보려고 하였습니다.
  - 테스트 코드를 작성한 후에 구현 코드를 작성하고, 구현된 코드를 리팩토링한다.
- 최대한 코드를 분리해보려고 했습니다.
  - 분리하고도 깔끔한 느낌?이 들지 않는 것 같습니다. 더 개선할만한 방향을 제시해주시면 감사하겠습니다!

2022-04-23 01:19 UTC, JunilHwang requested changes
안녕하세요 후동님! 자판기 미션을 함께하게된 리뷰어 황준일입니다 🙇‍♂️
제가 며칠동안 컨디션이 좋지 않았던 상태여서.. 리뷰를 이제서야 남기네요 ㅠㅠ 사전에 말씀드리지 못한점 죄송합니다 🙏

몇 가지 피드백 남겼는데
- 상수를 어떻게 관리하면 좋을지
- this를 어떤 상황에 써야 좋을지
- this를 쓴다면 class를 쓰는 것을 권장하고
- 꼭 this가 필요한 상황인지
- utils란 무엇인지
- 범용적인 코드란 무엇인지

이런 부분들에 대해서 고민해보시면 좋을 것 같아요!
자세한 내용은 코드리뷰를 확인해주세요 🙏
감사합니다 🙇‍♂️

2022-04-23 01:19 UTC, JunilHwang commented on src/js/InputValidation.js
> +};
```suggestion
const InputValidation = {
  isEmptyProductInput(name, price, quantity) {
    return !(name === '' || price === '' || quantity === '');
  },

  isUnder100Price(price) {
    return price >= 100;
  },

  isPriceInUnitsOf10Won(price) {
    return price % 10 === 0;
  },

  isUnderMinQuantity(quantity) {
    return quantity >= 1;
  },
};
```
이런식으로 표현할 수 있을 것 같아요!

2022-04-23 01:19 UTC, JunilHwang commented on src/js/Utils.js
> +}
이 함수들은 utils 성격을 띄고 있진 않은 것 같아요!

2022-04-23 01:19 UTC, JunilHwang commented on src/js/Utils.js
> +}
validation에서 throw를 던져주고,
외부에서는 throw를 catch하는 형태로 작성해준다면 더 좋을 것 같아요!

2022-04-23 01:19 UTC, JunilHwang commented on src/js/Utils.js
> +}
그리고 이 함수는 결국 false 아니면 undefined만 반환하는 것 같은데,
그렇다면 return false를 할 필요가 있을까요?

2022-04-23 01:19 UTC, JunilHwang commented on src/js/product.js
> +      </table>`;
아무것도 없는 템플릿 변수라면 차라리 함수 밖에 선언해도 무방할 것 같아요!

2022-04-23 01:19 UTC, JunilHwang commented on src/js/product.js
> +}
this를 쓸꺼라면 class 문법을 쓰는게 좋다고 생각합니다.
그리고 꼭 this가 필요한 상황일까요?
멤버변수로서 무언가 필요한 상황도 아닌 것 같고,
단순히 method가 필요한 상황 같은데
이건 꼭 method로 만들지 않아도 될 것 같아요!

2022-04-23 01:19 UTC, JunilHwang commented on src/js/product.js
> +  };
하나의 함수가 너무 많은 일을 하고 있어요!
더 작게 쪼개보면 어떨까요?

2022-04-23 01:19 UTC, JunilHwang commented on src/js/product.js
> +    if (duplicatedProuductNameIndex === Constants.NOT_FOUND_DUPLICATED_PRODUCT_NAME) {
`NOT_FOUND_DUPLICATED_PRODUCT_NAME` 이라는 상수는 결국 `product` 에서만 사용되는 것 같네요!

어디에서든 사용될 수 있는 상수라면 constants 라는 파일에 따로 관리하는게 좋을 것 같은데
정말 한 군데에서만, 특정 레이어에서만 사용되는 상수라면 해당 영역에 선언해서 관리해주는게 좋다고 생각해요 ㅎㅎ

2022-04-23 01:19 UTC, JunilHwang commented on src/js/product.js
> +    }
validateProductInputs 도 uitls이 아니라 이 파일 내에서 관리해야 좋았을 것 같아요

2022-04-23 01:19 UTC, JunilHwang commented on src/js/store.js
> +}
```suggestion
export function getLocalStorageProducts() {
  return JSON.parse(window.localStorage.getItem('products')) || [];
}
```
이렇게 표현할 수 있답니다!

2022-04-23 01:19 UTC, JunilHwang commented on src/js/store.js
> +}
'products' 라는 문자열도 상수로 만들어서 관리할 수 있을 것 같아요!

2022-04-23 01:19 UTC, JunilHwang commented on cypress/integration/product.test.js
> +    cy.get('#product-quantity-input').type(5);
상품을 추가하는 동작에 대한 함수를 만들어서 관리해주면 좋겠네요!

2022-04-23 01:19 UTC, JunilHwang commented on cypress/integration/product.test.js
> +  });
상품명, 금액, 수량 등 각각에 대해서 입력해보고 검증하는 로직이 있으면 좋을 것 같아요!

2022-04-23 01:19 UTC, JunilHwang commented on cypress/integration/product.test.js
> +
보통 이럴 땐 99 같은 경계값을 사용한답니다!

2022-04-23 01:19 UTC, JunilHwang commented on cypress/integration/product.test.js
> +  });
음수도 입력할 수 있을까요?

2022-04-23 01:19 UTC, JunilHwang commented on cypress/integration/product.test.js
> +  });
앞선 내용 처럼 경계값을 사용하면 좋을 것 같아요!

2022-06-05 05:37 UTC, pocojang approved these changes
장기간 진행되지는 않는 것 같아 이만 머지합니다
그동안 고생하셨습니다 :)

2022-06-05 05:37 UTC, merged