[클린코드 3기 원동휘] 자판기 미션 STEP 1
next-step/js-vending-machine pull request #48
Opened 2022-09-29 17:06 UTC by wondonghwi

안녕하세요 중간에 텀이 길었네요 다시한번 힘내서 자판기 미션을 시작하려고 합니다. 잘부탁드립니다!

어려움을 겪었던부분은 상품 목록을 유지하는 LS를 다루는 부분이었습니다. 
> 같은 상품명의 데이터를 추가하면 기존의 상품에 해당하는 데이터는 새로운 상품으로 대체된다.

라는 요구사항을 어떻게 작업해야할까 어려워하던도중 다른분들의 작업을 참고해서 아이디어를 얻어 "computed property name" 을 사용하는 방식으로 작업했습니다. 덕분에 엉망이던 구조도 싹 갈아엎었습니다.

아직 1단계라 많은 작업 내용은 없지만 많은 리뷰 부탁드립니다.!

- [x]  최초 상품 목록은 비워진 상태이다.
- [x]  상품명, 금액, 수량을 추가할 수 있다.
- [x]  상품명, 금액, 수량은 공백이 불가능하다.
- [x]  상품의 최소 수량은 1개여야 한다.
- [x]  상품의 최소 가격은 100원이며, 10원으로 나누어 떨어져야 한다.
- [x]  같은 상품명의 데이터를 추가하면 기존의 상품에 해당하는 데이터는 새로운 상품으로 대체된다. (이부분이 가장 어려웠음)
- [x]  사용자는 추가한 상품을 확인할 수 있다.
- [x]  상품 목록은 탭을 이동하여도 기존의 상품 목록이 유지되어야 한다.
- [x]  상품 목록은 새로고침해도 기존의 상품 목록이 유지되어야한다.

2022-10-03 15:40 UTC, pocojang requested changes
안녕하세요
@wondonghwi 👋 

교육기간이 종료되었지만 미션을 수행하고자하는 의지가 감동이네요
일단 코멘트 리뷰만 남겼으니 리뷰 반영하시면 다시 리뷰 요청해주세요

고생하셨습니다

2022-10-03 15:40 UTC, pocojang commented on README.md
> +  <h1 align="middle">원동휘 / 자바스크립트와 Cypress로 구현하는 자판기</h1>
👍

2022-10-03 15:40 UTC, pocojang commented on .eslintrc.js
> +  rules: {
재미있는 옵션을 많이 지정하셨네요
모두 동휘님이 고민해보시고 넣으신걸까요?

2022-10-03 15:40 UTC, pocojang commented on README.md
> +## 1 단계 요구사항
요구사항 정리 잘하셨네요 좋습니다

2022-10-03 15:40 UTC, pocojang commented on index.html
> +	<title>원동휘 / NEXTSTEP JavaScript Vending machine</title>
👍

2022-10-03 15:40 UTC, pocojang commented on index.html
> +<script type="module" src="./src/js/index.js"></script>
들여쓰기는 안하실까요?

2022-10-03 15:40 UTC, pocojang commented on src/css/index.css
> +    background-color: #f4f3f5;
컬러 관리에 대한 고민을 해보시는게 어떨까요?

2022-10-03 15:40 UTC, pocojang commented on src/js/constants/index.js
> +  BUTTON_CLASSNAME: 'button-menu',
`class name`인게 확실하면 `.prefix`가 있어야하지 않을까요~?
아니면 상수 키에서 `_CLASSNAME`을 제거하는게 통일 성이 있을 것 같습니다

2022-10-03 15:40 UTC, pocojang commented on src/js/constants/index.js
> +  ONE_H: 100,
불필요한 줄임말로 혼동을 줄 수 있을 것 같은데 어떻게 생각하실까요?!

2022-10-03 15:40 UTC, pocojang commented on src/js/index.js
> +      return null;
`null` 보다 더욱 좋은 무언가는 없을까요?!

2022-10-03 15:40 UTC, pocojang commented on src/js/index.js
> +  if (e.target.classList.contains(MENU.BUTTON_CLASSNAME)) {
`if` 조건을 더 추상화하면서 명시적으로 변경하실 수 있을까요?

2022-10-03 15:40 UTC, pocojang commented on src/js/service/ProductManageMenuService.js
> +    state[Storage.getCurrentTab()][name] = {
`Storage.getCurrentTab()`의 행위로 나오는 값은 예측이 되는데요
`state[Storage.getCurrentTab()]` 해당 값은 어떤 값이 들어올지 예측이 어려우니 더 구체적으로 명시하는게 어떨까요?

2022-10-03 15:40 UTC, pocojang commented on src/js/service/ProductManageMenuService.js
> +class ProductManageMenuService {
모든 메서드가 `Static`인데 굳이 클래스로 만들 이유가 있을까요?

2022-10-03 15:40 UTC, pocojang commented on src/js/service/ProductManageMenuService.js
> +  static setProductListState(name, price, count) {
인자를 3개나 받고 있으니 매개변수는 객체로 받는게 어떨까요?

2022-10-03 15:40 UTC, pocojang commented on src/js/service/VendingMachineManageMenuService.js
> +    this.coinState = this.state[Storage.getCurrentTab()][STORAGE_KEY.COINS];
`coinState`라는 네이밍으로 필드 명을 정의하면 모든 필드에 `-state suffix`를 제공하실건가요~?

2022-10-03 15:40 UTC, pocojang commented on src/js/service/VendingMachineManageMenuService.js
> +        price -= randomAmount * coin;
루프를 돌때마다 매번 변수에 할당하는 방식이 아닌 다른 방식은 어떨까요?!

2022-10-03 15:40 UTC, pocojang commented on src/js/storage/index.js
> +    return JSON.parse(localStorage.getItem('state')) || initState;
방어 처리 좋네요 👍 
다만 `state`는 너무 넓은 범위의 키라서 다른 애플리케이션과 중복될 수 있지 않을까요?

2022-10-03 15:40 UTC, pocojang commented on src/js/storage/index.js
> +    localStorage.setItem('tab', tab);
로컬 스토리지는 애플리케이션 단위로 관리되는게 좋을텐데 키를 여러개 가져가는 것이 유용할까요?

2022-10-03 15:40 UTC, pocojang commented on src/js/utils/index.js
> +const removeSpaces = string => string.replace(/\s/g, '');
정규식 추상화 좋네요 👍

2022-10-03 15:40 UTC, pocojang commented on src/js/validate/index.js
> +const generateError = message => {
불필요한 추상화 같은데 어떻게 생각하실까요?

2022-10-03 15:40 UTC, pocojang commented on src/js/view/ProductManageMenu.js
> +  constructor($app) {
`$app`이 무엇인지 더 구체적으로 명시되면 좋겠습니다!

2022-10-03 15:40 UTC, pocojang commented on src/js/view/ProductManageMenu.js
> +  productManagerMenuTemplate = `
이렇게 클래스 내부에 덩그러니 배치하신 이유가 있을까요?

2022-10-03 15:40 UTC, pocojang commented on src/js/view/ProductManageMenu.js
> +  static addProductInventoryTemplate(name, value) {
굳이 클래스 내부에 있을 필요가 있을까요?

2022-10-03 15:40 UTC, pocojang commented on src/js/view/ProductManageMenu.js
> +        ProductManageMenu.addProductInventoryTemplate(tabId, ProductManageMenuService.getCurrentTabState()[tabId])
`tabId`가 없을 때의 처리는 없을까요~?

2022-10-03 15:40 UTC, pocojang commented on src/js/view/ProductManageMenu.js
> +    const [name, price, count] = productInputValue;
```suggestion
    const [name, price, count] = new FormData(e.target).getAll(NAME.PRODUCT_INPUT);
```
이렇게도 가능할까요?

2022-10-03 15:40 UTC, pocojang commented on src/js/view/ProductManageMenu.js
> +      const inputCondition = checkPriceUnit(parseInt(price, 10));
`10` 명시 좋습니다 👍

2022-10-03 15:40 UTC, pocojang commented on src/js/view/ProductManageMenu.js
> +      window.location.reload(); // TODO
무엇을 `// TODO`한다는 것인지 명시하는게 어떨까요?

2022-10-03 15:40 UTC, pocojang commented on src/js/view/ProductManageMenu.js
> +      alert(error.message);
경고 이외에 액션을 제공할 필요는 없을까요?

2022-10-03 15:40 UTC, pocojang commented on src/js/view/ProductPurchaseMenu.js
> +  }
여태까지의 구조를 봐왔을때는 이 메서드도 `static`이 어울려보이는데 나뉜 이유가 있을까요?

2022-10-03 15:40 UTC, pocojang commented on src/js/view/VendingMachineManageMenu.js
> +  vendingMachineManageMenuTemplate = `
흠.. 아무리 봐도 클래스 내부에 있을 이유가 있을지 모르겠군요

2022-10-03 15:40 UTC, pocojang commented on src/js/view/VendingMachineManageMenu.js
> +    $vendingMachineForm.reset();
👍

2022-10-03 15:40 UTC, pocojang commented on src/js/view/VendingMachineManageMenu.js
> +    $vendingMachineChargeAmount.textContent = ProductManageMenuService.getCurrentTabState()[STORAGE_KEY.AMOUNT];
`innerText`, `textContent`, `innerHTML`의 차이를 알고 계실까요~?

2022-10-04 13:08 UTC, wondonghwi commented on .eslintrc.js
> +  rules: {
네 현석님 하나나 추가했습니다! 이번에 airbnb eslint를 처음 사용해봤는데 **너무 강력하게 경고를 잡더라구요** ㅎㅎ 

그래서 1단계 계산기부터 차곡차곡 이경고까진 필요없다 싶을때마다 rules에 하나하나 추가하고 다음미션때
prettier와 eslint를 그대로 가져온 결과입니다 ㅎㅎ

2022-10-04 13:11 UTC, wondonghwi commented on index.html
> +<script type="module" src="./src/js/index.js"></script>
저는 웹스톰 IDE를 쓰는데 
웹스톰에는 prettier를 자동으로 안해주고 따로 옵셔지정을 해야해서 옵션지정하고 저장해야하는데 누락했네요 감사합니다!
formatting 커밋 추가할게요!

<img width="358" alt="image" src="https://user-images.githubusercontent.com/55338435/193827816-6661c2fd-4b8f-46d9-8471-3b92edea49d0.png">

2022-10-04 13:35 UTC, wondonghwi commented on src/css/index.css
> +    background-color: #f4f3f5;
제공된 css라서 따로 관리를 할 생각자체를 하지못했습니다.
컬러 관리 일깨워주셔서 감사해요!

2022-10-04 13:37 UTC, wondonghwi commented on src/js/constants/index.js
> +  ONE_H: 100,
ONE_H -> ONE_Hundred 였는데 짧게쓰고싶어서 줄였다가 History를 잘모르는사람이나, 미래의 저가봤을때 충분히 혼동이 올 것 같네요! 명시적으로 수정하겠습니다!

2022-10-04 13:42 UTC, wondonghwi commented on src/js/view/ProductManageMenu.js
> +    const [name, price, count] = productInputValue;
productInputValue을 사용하는 다른곳이 없는데 굳이 productInputValue변수를 생성할 이유가없었네요 감사합니다 
제안주신내용으로 적용했습니다! 🫡

2022-10-04 13:45 UTC, wondonghwi commented on src/js/view/ProductManageMenu.js
> +      window.location.reload(); // TODO
개발하다가 써놓은건데 뒤에 문구는 지우고 // TODO 는 안지웠네요! TODO자체를 지우겠습니다~

2022-10-04 14:01 UTC, wondonghwi commented on src/js/service/ProductManageMenuService.js
> +  static setProductListState(name, price, count) {
네 객체로 받도록 수정했습니다! 3개이상정도 되면 객체로관리하는것도 좋겠네요!

객체를 통해 인자를 받게 된다면 parameter의 순서와 관계없이 값을 받아서 사용할 수 있어서 해당 함수를 사용할 때의 실수를 줄 일 수 있을것같아서 객체로 받는걸 제안주신것이 맞을까요?

2022-10-04 14:14 UTC, wondonghwi commented on src/js/service/ProductManageMenuService.js
> +class ProductManageMenuService {
먼저 제가 Class 사용에 아직 미숙해서 Class를 거의 안쓰다가 이번 넥스트스텝 과정부터 사용하기 시작했는데요,

Class로 사용하면 특정메소드들을 그룹핑하는 효과가 있다고 생각됩니다. 

그래서 LocalStorage에 get과 set 하는 함수를 그룹으로 만들고 싶어서 Class로 작성했습니다.

2022-10-04 14:30 UTC, wondonghwi commented on src/js/view/VendingMachineManageMenu.js
> +  vendingMachineManageMenuTemplate = `
다시 생각해보니까 그렇네요

사실 처음에는 클래스 내부에서만 사용하니까 클래스내부에 만들어놓았는데 

해당 클래스의 코드가 길어짐에 따라서 코드를 분석하기도 복잡해지고, Template도 Template선언끼리 묶는게 좋을것같네요!

그래서 Template관련 코드들은 따로 Template.js파일만들어서 분리했습니다!

2022-10-04 14:33 UTC, wondonghwi commented on src/js/view/ProductPurchaseMenu.js
> +  }
> 여태까지의 구조를 봐왔을때는 이 메서드도 static이 어울려보이는데 나뉜 이유가 있을까요?

여기서 나뉜 이유라는게 잘 이해가가지않습니다. 

해당 파일은 이렇게 3개의 탭이 잘 동작하는지 확인을위해 미리 구조만 잡아놓은 상황입니다.
해당 탭은 Step1,2에서 작업사항이 아니라서 아직 따로작업은 하지않았습니다

<img width="293" alt="image" src="https://user-images.githubusercontent.com/55338435/193847226-61ae29c1-b8da-40e0-a0a2-22c95fcc3668.png">

2022-10-04 14:41 UTC, wondonghwi commented on src/js/view/ProductPurchaseMenu.js
> +  }
해당 Class에서 static으로 메소드를 정의하면 어떻게 처음부터 

this.initRenderer(); 처럼 초기화 할 수있을지 모르겠어요 그래서  this.initRenderer로 사용했습니다.

static으로 바꾸고 처음 CLass의 메소드가 실행되도록 하는 방법이있을까요?

2022-10-04 14:52 UTC, wondonghwi commented on src/js/view/ProductManageMenu.js
> +      alert(error.message);
뭐가있을까 고민하다가 아래와같이 에러가발생했을때 가격input에서 에러가 발생한거니 가격input창으로 focus해주는작업을추가했습니다.!

돈통충전에는 Input이 하나밖에없어서 아래코드를 따로 추가하지않았습니다!

const priceInput = document.querySelector('#product-price-input');
priceInput.focus();

2022-10-04 14:53 UTC, wondonghwi commented on src/js/view/ProductManageMenu.js
> +  static addProductInventoryTemplate(name, value) {
template.js로 뺐습니다!

2022-10-04 14:53 UTC, wondonghwi commented on src/js/view/ProductManageMenu.js
> +  productManagerMenuTemplate = `
template.js로 뺐습니다!

2022-10-04 14:58 UTC, wondonghwi commented on src/js/view/ProductManageMenu.js
> +  constructor($app) {
react를 사용할때는 app이라는 id위에 Dom을 그리기때문에 react적 사고로 app이 명시적이라고 생각했습니다.

혹시 main같은게 더 명시적일까요? app으로 id를 지정하고 실제 사용은 Main으로 하면 그것도 그것나름대로 혼란이 올수 있지않을까 생각해보았습니다 🤔

2022-10-04 15:17 UTC, wondonghwi commented on src/js/index.js
> +      return null;
해당 switch문에서 default가 나올 경우가 없다고 판단해서 return null로 넣었습니다. 
차라리 default가 나올일이 아에없으니 default문을 지우는게 나을것같은데 현석님은 어떻게 생각하시나요?

```js
window.onload = () => {
  if (LocalStorage.getCurrentTab()) renderTab();
};
```
이렇게 첫 onLoad때도 방어코드가 있어서 switch문에 default가 의미없다 느껴지네요

2022-10-04 15:18 UTC, wondonghwi commented on src/js/validate/index.js
> +const generateError = message => {
그렇네요 전혀 불필요한 추상화였네요! 짚어주셔서 감사합니다

2022-10-04 15:21 UTC, wondonghwi commented on src/js/view/ProductManageMenu.js
> +        ProductManageMenu.addProductInventoryTemplate(tabId, ProductManageMenuService.getCurrentTabState()[tabId])
tabId는 항상 존재하지않을까요?!

map이 돈다는건 배열안의 반복될 요소가 있다는것이고 그럼으로써 tabId는 map이 돌려면 항상 존재한다고 가정할 수 있는것같은데 
따로 tabId가 없을때 조건처리가 필요할지 의문입니다 🤔

2022-10-04 15:25 UTC, wondonghwi commented on src/js/storage/index.js
> +    return JSON.parse(localStorage.getItem('state')) || initState;
그렇네요!! 
좀더 좁혀들어가서 vendingMachineState로 LocalStorage key를 변경했습니다!

2022-10-04 15:29 UTC, wondonghwi commented on src/js/storage/index.js
> +    localStorage.setItem('tab', tab);
리뷰주신의도는 tab과 state 이렇게 두개로 나누고 or 여러개로 나누면 프로젝트 단위가 커졌을때 관리해야할 LocalStorage가 많아지니까 관리가 점점 더 어려워져서 

가능한한 애플리케이션단위로 하나의 key로 사용하는것이 좋을 수 있다는 의미로 리뷰주신게 맞을까요?

실무에서도 프로젝트가 점점 커지면서 LocalStorage가 너무많아서 슬슬 감당이 안되던차에 좋은 인사이트를 얻은것같습니다 감사합니다.
이부분은 더 고민해볼게요!

2022-10-04 15:32 UTC, wondonghwi commented on src/js/service/VendingMachineManageMenuService.js
> +    this.coinState = this.state[Storage.getCurrentTab()][STORAGE_KEY.COINS];
모든필드에 -state suffix 까지는 생각하지않았고 
coinState바꾸기전 코드가 너무 반복되어서 coinState라는 필드를 만들었는데 

이렇게 계속 반복된다고 필드로 따로 빼는건 별로좋지못할까요??

2022-10-04 15:38 UTC, wondonghwi commented on src/js/index.js
> +  if (e.target.classList.contains(MENU.BUTTON_CLASSNAME)) {
```js
const { className } = e.target;
if (className === MENU.BUTTON) {}
```
  위 코드처럼 수정해보았는데 명시적으로 변경된게 맞는건지 확신이없네요 혹시 더 좋은방법이 있을까요?!

2022-10-04 15:45 UTC, wondonghwi commented on src/js/service/ProductManageMenuService.js
> +    state[Storage.getCurrentTab()][name] = {
저도 리뷰내용보고 그렇게 느껴져서 이렇게 필드하나만들어서 필드명으로 어떤값이 들어올지 더 구체적으로 명시해주었습니다!

this.getStateByCurrentTab = Storage.getStateData()[Storage.getCurrentTab()];

2022-10-04 15:50 UTC, wondonghwi commented on src/js/service/VendingMachineManageMenuService.js
> +        price -= randomAmount * coin;
이 부분은 감이 안잡히네요 ㅠㅠ

현재 로직에서 루프돌때마다 변수를 할당하지않는방법을 넣을수가없을것같아서 
아에 로직 자체가 변경되어야할것같은데 

더 고민해봐야할것같네요 😥

2022-10-04 16:03 UTC, wondonghwi commented on src/js/view/VendingMachineManageMenu.js
> +    $vendingMachineChargeAmount.textContent = ProductManageMenuService.getCurrentTabState()[STORAGE_KEY.AMOUNT];
innerHTML은 Html 전체를 아에 덮어쓰는것이고, 그래서 기존 html내용은 그대로 납두고 새로운내용만 따로 추가하고싶은경우에는 
insertAdjacentHTML을 사용하는것으로 이해하고있고,

textContent, innerText은 둘다 요소 내부의 text를 변경해주는것으로 알고있습니다.
또한 innerText를 사용하지않고 textContent를 사용한 이유는 이전에 검색했을때 textContent가 더 오래되고, 의미에맞다는 글을 읽은기억이 있어서 textContent를 주로사용했는데요

> innerText, textContent, innerHTML의 차이
이부분에 대해서는 따로 검색해서 완전한 지식으로 습득해보겠습니다! !

2022-10-06 01:08 UTC, wondonghwi commented on src/js/view/VendingMachineManageMenu.js
> +    $vendingMachineChargeAmount.textContent = ProductManageMenuService.getCurrentTabState()[STORAGE_KEY.AMOUNT];
**< 검색 이후 >**
## innerHtml 
- 요소 전체를 변경하거나 읽어오는데 사용 (elements, 공백포함)
- 요소 전체를 변경하는게 아닌 Html을 삽입 하려면 insertAdjacentHTML을 사용

## textContent
- 요소 를 포함한 모든 요소 의 내용을 가져옵니다 . 
- innerText와 비교해 성능우위
- textContent를 사용하면 XSS 공격을 방지가능
- 공백이 그대로 반환


## innerText 
- 대조적으로 "사람이 읽을 수 있는" 요소만 표시
- innerText 숨겨진" 요소의 텍스트를 반환하지 않음 + 공백이 제거됨(trim)
- innerText는 css 스타일을 고려하기때문에 리플로우가 트리거됨 (성능저하)

상황에 따라 다르게 사용되어야겠다고 생각되네요 왠만하면 textContent 
공백이 제거된 문자를 이용해야하면 innerText를 사용할것같습니다.!

2022-10-10 11:44 UTC, pocojang commented on index.html
> +<script type="module" src="./src/js/index.js"></script>
저도 젯브레인 좋아합니다!
다만 젯브레인 설정과 ESLint & Prettier 설정이 잘 안붙어요.
설정 파일과 잘 연결되어있는지 체크해보세요 :)

2022-10-10 11:44 UTC, pocojang commented on src/js/index.js
> +      return null;
`default`는 엄청나게 의미 있어요
다만 `If`문으로 변경한다면 상관없긴하겠네요!!

2022-10-10 11:45 UTC, pocojang commented on src/js/index.js
> +  if (e.target.classList.contains(MENU.BUTTON_CLASSNAME)) {
오 이것도 괜찮네요?
하지만 변수에 담아서 명시적으로 표현해도 좋겠어요
클레스 네임이 메뉴 버튼인 경우에 다른 의미가 있을 수 있으니까요

2022-10-10 11:46 UTC, pocojang commented on src/js/service/ProductManageMenuService.js
> +    state[Storage.getCurrentTab()][name] = {
`getStateByCurrentTab` 네이밍은 함수나 메스드로 느껴지는 네이밍 같지 않나요~?

2022-10-10 11:46 UTC, pocojang commented on src/js/service/ProductManageMenuService.js
> +class ProductManageMenuService {
그럼 싱글 리터럴 객체로 그룹화하는 것과는 어떤 점이 다를까요~?

2022-10-10 11:48 UTC, pocojang commented on src/js/service/VendingMachineManageMenuService.js
> +    this.coinState = this.state[Storage.getCurrentTab()][STORAGE_KEY.COINS];
현재까지는 괜찮지만 확장을 열어둔 다는 관점에서 생각해보면 좋겠어요
해당 클래스의 멤버 변수가 더 다양한 종류로 생기면 어떻게 될까요?

2022-10-10 11:48 UTC, pocojang commented on src/js/service/VendingMachineManageMenuService.js
> +        price -= randomAmount * coin;
저도 어려울 것 같습니다 ㅎㅎ
다만 이번 미션에서 꼭 고쳐보시는 것을 권합니다 :)

2022-10-10 11:49 UTC, pocojang commented on src/js/view/ProductManageMenu.js
> +  constructor($app) {
그것보다는 매개변수로 들어오는 것이 무엇인지 누구든 알아볼 수 있도록 하는게 어떨까요?

2022-10-10 11:50 UTC, pocojang commented on src/js/view/ProductManageMenu.js
> +        ProductManageMenu.addProductInventoryTemplate(tabId, ProductManageMenuService.getCurrentTabState()[tabId])
정말 어떠한 상황에서도 걱정이 없다면 괜찮슨비다
다만 서버에서 `tabId`를 받아오고 네트워크가 지연되거나 끊기는 경우나 데이터가 옳지 않으면 어떨까? 상상해보세요!

2022-10-10 11:51 UTC, pocojang commented on src/js/view/ProductManageMenu.js
> +      alert(error.message);
아주 좋습니다 :)

2022-10-10 11:52 UTC, pocojang commented on src/js/view/ProductPurchaseMenu.js
> +  }
@wondonghwi 님이 저보다는 더 잘알아야겠죠 ㅎㅎ
다만 전혀 동적인 바인딩이 필요 없으니 애매하긴한데요~?

2022-10-10 11:52 UTC, pocojang commented on src/js/view/VendingMachineManageMenu.js
> +    $vendingMachineChargeAmount.textContent = ProductManageMenuService.getCurrentTabState()[STORAGE_KEY.AMOUNT];
오호
정말 좋습니다 :)

정리하신 것도 좋아요!!

2022-10-10 13:08 UTC, pocojang approved these changes
@wondonghwi 님
의미와 근거를 가지고 코드가 수정되고 있어서 보기 좋네요
다만 `view`, `service` 계층에 대한 정리와 고민이 있었으면 좋겠어요
도식화로 그리고 함께 토론하면 더 좋겠죠?
추가적으로 테스트 코드가 없어 아쉽네요 :)

그럼 다음 스텝에서 뵐게요!

2022-10-10 13:08 UTC, merged