[클린코드 3기 원동휘] 자판기 미션 STEP 3 & STEP 4
next-step/js-vending-machine pull request #49
Opened 2022-10-22 17:24 UTC by wondonghwi

현석님안녕하세요! 드디어 마지막까지 왔습니다. 넥스트스텝 기간이 끝났음에도 불구하고 리뷰해 주심에 진심으로 감사드립니다!. 
마지막 단계까지 오면서 정말 많이 배우고, 깨닫는 시간이 된 것 같아서 감회가 새롭네요!! 

**자판기 3 & 4 단계 코드리뷰 부탁드립니다.!!**

모든 작업 완료했습니다. 많은 리뷰부탁드립니다. 한번에 작업하느냐고 마지막 commit은 기능별로 commit을 나눠서 작업하지못한점이 유일하게 아쉽네요 ㅠㅠ 

많은 리뷰 부탁드립니다 감사합니다!

2022-10-30 17:09 UTC, pocojang requested changes
@wondonghwi 👋 
정말 고지가 눈앞에 있네요

## 코멘트 외의 리뷰

### 동사 사용

네이밍에 사용되는 동사의 의미를 고민해보시는게 어떠실지?! 제안해봅니다

### 반복 리뷰

이미 스텝1~2에 했던 리뷰를 반복하는 제 모습이 보이네요!
댓글로 다시 소통해보시죠

### let 임시 변수 제거

굳이 없어도 될 것 같고 이쯤은 정말 제거할 수 있어야 된다? 라는 생각이 듭니다.
만약 꼭 사용해야한다면 저를 설득해보시는게 어떠신지..?!

### 객체 깊이

객체의 깊이가 너무나도 깊어지고 있어요
가독성도 떨어지고 저는 정말 안전한 값일까? 라는 생각에 불안하기도 합니다.

### 문법을 의미있게 사용하는 방법

```js
Storage.getStateData()[MENU.VENDING_MACHINE_MANAGE];
// vs
Storage.getStateData(MENU.VENDING_MACHINE_MANAGE);
```

언어를 떠나서 문법으로 봤을때 말이죠
아래의 고민을 해보고 위의 코드를 비교해보시는게 어떨까요?
한번 제안해봅니다 ㅎㅎ

- `.`는 무엇일까요?
- `()`는 무엇일까요?
- `[]`는 무엇일까요?
- `.`는 어떤 기능을 가질까요?
- `()`는 어떤 기능을 가질까요?
- `[]`는 어떤 기능을 가질까요?
- `.`에 어떤 역할을 부여하셨나요?
- `()`에 어떤 역할을 부여하셨나요?
- `[]`에 어떤 역할을 부여하셨나요?

---

나머지는 댓글 리뷰 확인해주세요!

2022-10-30 17:09 UTC, pocojang commented on src/js/index.js
> +      buttonMenu[0].classList.add('clicked');
`buttonMenu[N]`으로 접근하는 선택은 너무 암시적인 것 같아요!
더 좋은 방법이 없을까요?

2022-10-30 17:09 UTC, pocojang commented on src/js/index.js
> +const buttonMenu = document.querySelectorAll('.button-menu');
`DOM`의 경우 `$-prefix`를 사용하시는 것 같던데 여기서 예외되는 이유가 궁금하군요!

2022-10-30 17:09 UTC, pocojang commented on src/css/index.css
> +}
컬러 팔레트 관리가 아쉽네요 😢

2022-10-30 17:09 UTC, pocojang commented on src/js/service/ProductPurchaseService.js
> +    const price = parseInt(this.stateData[MENU.PRODUCT_MANAGE][product][STORAGE_KEY.PRICE], 10);
객체의 `depth`가 과도하게 길어지는데 어떻게 생각하시나요~?

2022-10-30 17:09 UTC, pocojang commented on src/js/service/ProductPurchaseService.js
> +    if (count > 0 && purchasePrice >= price) {
조건문 추상화가 가능할까요?

2022-10-30 17:09 UTC, pocojang commented on src/js/template/index.js
> +      <td><button class="purchase-product-button" data-product=${name} ${
[data-*](https://developer.mozilla.org/ko/docs/Web/HTML/Global_attributes/data-*)를 사용할때는 정말 꼭 필요한지 고민해보시길 바래요~

2022-10-30 17:09 UTC, pocojang commented on src/js/template/index.js
> +const generateProductPurchaseTemplate = (name, value) => {
요 템플릿은 `generate`해주는 개념은 없어보이는데 어떻게 생각하시나요?

2022-10-30 17:09 UTC, pocojang commented on src/js/template/index.js
> +const generateCashBoxChangeTemplate = remains => `
특히 이 템플릿은 더더욱 `generate`해주는 개념이 전혀 없어보이지 않나요?!

2022-10-30 17:09 UTC, pocojang commented on src/js/template/index.js
> +	      <input type="number" name="purchase-amount" id="purchase-input" min="10" autofocus/>
많은 `HTML` 표준 속성을 사용하셨네요 👍

2022-10-30 17:09 UTC, pocojang commented on src/js/view/ProductManageMenu.js
> +  static addProductList(e) {
오 어떤 차이가 있으셨나요?

2022-10-30 17:09 UTC, pocojang commented on src/js/view/ProductManageMenu.js
> +    $productContainer.reset();
👍

2022-10-30 17:09 UTC, pocojang commented on src/js/view/ProductManageMenu.js
> +    $productForm.addEventListener('submit', e => ProductManageMenu.addProductList.bind(this)(e));
`(e)`를 따로 넘겨줘야하는 이유가 궁금하네요!

2022-10-30 17:09 UTC, pocojang commented on src/js/view/ProductPurchaseMenu.js
> +      purchaseInput.focus();
사용자를 위한 에러처리까지 좋네요 👍

2022-10-30 17:09 UTC, pocojang commented on src/js/view/ProductPurchaseMenu.js
> +    $coinReturnButton.addEventListener('click', () => this.returnRemain());
```suggestion
    const $productPurchaseForm = document.querySelector('#product-purchase-form');
    const $productInventoryContainer = document.querySelector('#product-inventory-container');
    const $coinReturnButton = document.querySelector('#coin-return-button');

    $productPurchaseForm.addEventListener('submit', e => this.insertAmount.bind(this)(e));
    $productInventoryContainer.addEventListener('click', e => this.buyProduct.bind(this)(e));
    $coinReturnButton.addEventListener('click', () => this.returnRemain());
```

이건 어떨까요?

2022-10-30 17:09 UTC, pocojang commented on src/js/service/ProductPurchaseService.js
> +  remainService() {
하는 일이 너무 많은 함수라고 보이네요
리팩터링이 필수로 되었으면 좋겠는데 어떻게 생각하시나요?

2022-10-30 17:09 UTC, pocojang commented on src/js/service/ProductPurchaseService.js
> +  setButProduct(product) {
`setButProduct()`에서 `But` 은 무엇을 의미할까요?

2022-10-30 23:41 UTC, wondonghwi commented on src/js/service/ProductPurchaseService.js
> +  setButProduct(product) {
오타였습니다! .. 잡아주셔서 감사합니다 Buy를 의도했습니다 수정할게요!!

2022-10-30 23:45 UTC, wondonghwi commented on src/js/view/ProductPurchaseMenu.js
> +    $coinReturnButton.addEventListener('click', () => this.returnRemain());
Dom선택 변수는 변수끼리, 이벤트 리스너는 이벤트리스너 끼리 모으는게 더 가독성도 좋고 코드 파악하기도 좋아보이네요! 이렇게 수정하겠습니다 👍

2022-10-30 23:49 UTC, wondonghwi commented on src/js/view/ProductManageMenu.js
> +    $productForm.addEventListener('submit', e => ProductManageMenu.addProductList.bind(this)(e));
네 물론 e를 명시적으로 넘겨주지 않아도 자동으로 e가 들어가지만 
더 명확하게 event가 전달됨을 나타내기 위해 적었는데

지금보니 사실 굳이 있을필요가 없겠네요!

함수로 다른 매개변수를 넘길경우는 필요하지만 event만 넘길때는 필요없으므로 제거하겠습니다!

2022-10-31 08:44 UTC, wondonghwi commented on src/js/index.js
> +const buttonMenu = document.querySelectorAll('.button-menu');
$를 누락한 상황입니다. 꼼꼼하게 살피지 못했네요! 수정했습니다.!

2022-10-31 09:01 UTC, wondonghwi commented on src/js/view/ProductManageMenu.js
> +  static addProductList(e) {
네 Class를 사용할때 저는 Class의 필드를 사용하나, 하지않나로 구분합니다.

Class의 필드를 사용하지않는경우 static으로 메소드를 정의하고, 그렇지않은경우 static으로 메소드를 정의합니다.

static으로 정의한 경우 클래스의 데이터를 가져오지 못하고, 객체의 인스턴스를 생성해도 정적 메서드는 클래스의 데이터를 가져오지 못하므로 Class를 인스턴스를 공유하기위한 목적보다 함수를 그룹화 하고 그 그룹화된 내용안에 util함수처럼 사용하기 위해
static으로 정의했습니다. 

위와 같은 경우도 Class의 메소드이지만 Class의 필드를 사용하지않기때문에 static으로 작업했습니다!

2022-10-31 09:16 UTC, wondonghwi commented on src/js/template/index.js
> +      <td><button class="purchase-product-button" data-product=${name} ${
네 감사합니다.
[data-*](https://developer.mozilla.org/ko/docs/Web/HTML/Global_attributes/data-*)
많은 생각을 하지 못하고 당연하게 사용했는데 

data-*속성을 추가함으로써, 평범한 HTML 요소조차 복잡하고 강력한 프로그램 객체가 될 수 있습니다. 라고도 나와있네요

현재 상황에서는 localStorage의 key를 찾아가는 방식으로 사용하고있고 꼭 data-*가 아니어도 된다 판단되어 name으로 변경했습니다.

2022-10-31 09:23 UTC, wondonghwi commented on src/js/template/index.js
> +const generateProductPurchaseTemplate = (name, value) => {
저도 다시 보니 generate는 아닌것같네요 하지만 template을 함수로 만들었기때문에 함수명에 동사를 추가하는것으로 
template을 가져오다 해서 변수명의 generate를 get으로 변경했습니다.

2022-10-31 09:32 UTC, wondonghwi commented on src/js/service/ProductPurchaseService.js
> +    if (count > 0 && purchasePrice >= price) {
두 조건을 어떻게 추상화해서 더 줄일 수 있을지 떠오르지 않아서 아래처럼 변수로 의미전달 리팩토링했습니다.
혹시 해당조건을 추상화 하는 다른 방법이있을까요?

const purchasableCondition = count > 0 && purchasePrice >= price;

if (purchasableCondition) {}

2022-10-31 09:43 UTC, wondonghwi commented on src/js/index.js
> +      buttonMenu[0].classList.add('clicked');
맞네요! 이미 처음부터 각각 tab에 id를 정의했으니 더 명시적으로 id를 이용해서 접근하는 방식으로 수정했습니다.

2022-11-01 09:34 UTC, wondonghwi commented
@pocojang 현석님 안녕하세요 다시한번 리뷰 요청드립니다!

> 객체 깊이
> 객체의 깊이가 너무나도 깊어지고 있어요
> 가독성도 떨어지고 저는 정말 안전한 값일까? 라는 생각에 불안하기도 합니다.

에 대한 코멘트를 주셨습니다. 객체가 깊어지게 된 의도는 하나의 stoargeKey로 LocalStorage값을 관리하기 때문에 깊어지게 되었습니다. 하지만 하나의 StorageKey로 LocalStorage를 관리하는것은 의도한점입니다.
그래서 더 명시적으로 StorageService를 만들어서 LocalStorage의 값을 다루는데 함수를 통해서 다룰 수 있도록 모두 리팩토링했습니다. (이 과정이 시간이 오래걸렸습니다) 
또 한  StorageService로 리팩토링 하면서 

문법을 의미있게 사용하는 방법
Storage.getStateData()[MENU.VENDING_MACHINE_MANAGE];
// vs
Storage.getStateData(MENU.VENDING_MACHINE_MANAGE);

코멘트 주신 내용을 계속 생각해보면서 메소드를 만들고 매개변수로 넘길 수 있는건 매개변수로 넘겨서 사용할 수 있도록 많이 고민했습니다!

> let 임시 변수 제거
> 굳이 없어도 될 것 같고 이쯤은 정말 제거할 수 있어야 된다? 라는 생각이 듭니다.
> 만약 꼭 사용해야한다면 저를 설득해보시는게 어떠신지..?!

해당 코멘트에 대해 말씀드리면 아래와 같이 두개의 코드에서 let을 사용하는데 
```
let purchasePrice = StorageService.getStorageProductPurchase(this.stateData, STORAGE_KEY.PURCHASE_PRICE);
let [COIN_VALUE_10, COIN_VALUE_50, COIN_VALUE_100, COIN_VALUE_500] = Object.values(coins);
```
whille반복문을 돌면서 해당 변수의 값을 계속해서 변경해가면서 while반복문을 도는것을 의도해서 
의도한 let입니다. 그리고 또한 전역으로 let을 사용하는것이 아니라 
remainService메소드 내부에서만 let으로 변수를 정의해서 사용하기 때문에 의도에 맞게 사용하면 더욱 더 괜찮다고 생각됩니다.

즉 제가 사용한 let은 의도적으로  반복돌면서변수의 값을 바꿔주기위해 사용했고, 전역 변수로 선언한것도 아니고 메소드 내부에서 사용한 변수이기 때문에 let 임시 변수 제거는 하지않았습니다.

만약 꼭 사용해야한다면 저를 설득해보시는게 어떠신지..?! 에 대한 코멘트입니다 🫡

2022-11-01 09:43 UTC, wondonghwi commented on src/js/service/ProductPurchaseService.js
> +  remainService() {
리팩토링을 한번 거친 메소드입니다. 😭

remainService()함수 처음 작성이후 해당 메소드에서 리팩토링해서 함수 분리할 수 있는 내용을 모두 분리했습니다.! 
그래도 부피가 크긴하네요 ㅠㅠ

2022-11-01 09:44 UTC, wondonghwi commented on src/js/service/ProductPurchaseService.js
> +    const price = parseInt(this.stateData[MENU.PRODUCT_MANAGE][product][STORAGE_KEY.PRICE], 10);
아래에 코멘트 남긴대로 최대한 함수로 안전하게 접근할 수있도록 리팩토링과정을 거쳤습니다. 
하나의 LocalStorageKey로 모든 state를 관리하려니까 많이 깊어지네요ㅠㅠ

2022-11-08 11:34 UTC, pocojang commented on src/js/service/ProductPurchaseService.js
> +    const price = parseInt(this.stateData[MENU.PRODUCT_MANAGE][product][STORAGE_KEY.PRICE], 10);
제 개인적인 생각에는 `LocalStorageKey`와는 관계가 없다? 라고 생각합니다!
왜그럴까요?!

2022-11-08 11:34 UTC, pocojang commented on src/js/service/ProductPurchaseService.js
> +    if (count > 0 && purchasePrice >= price) {
`is-`로 시작해도 괜찮을 것 같습니다 :)

2022-11-08 11:34 UTC, pocojang commented on src/js/view/ProductManageMenu.js
> +    $productForm.addEventListener('submit', e => ProductManageMenu.addProductList.bind(this)(e));
오호 이미 그 이유를 아시면 됐습니다 ㅎㅎ

2022-11-08 11:35 UTC, pocojang commented on src/js/template/index.js
> +      <td><button class="purchase-product-button" data-product=${name} ${
맞아요 ㅎㅎ
무조건 사용하지말자라는 의미의 메세지는 아니였습니다.
인지하고 사용하는 것과 무의식적으로 사용하는 것은 다르니까요!

2022-11-08 11:36 UTC, pocojang commented on src/js/template/index.js
> +const generateProductPurchaseTemplate = (name, value) => {
👍

2022-11-08 11:37 UTC, pocojang commented on src/js/view/ProductManageMenu.js
> +  static addProductList(e) {
음 사실 아직도 이해가 안되는 것은 사실이지만 제 개인적인 생각일 수 있는 것 같아요.
하지만 @wondonghwi 님의 근거가 있다는 것에 만족합니다 👍

2022-11-08 11:37 UTC, pocojang commented on src/js/view/ProductPurchaseMenu.js
> +    $coinReturnButton.addEventListener('click', () => this.returnRemain());
취향 차가 있을 수 있겠지만 저는 선언을 위에 모아놓는 것을 선호한답니다 ㅎㅎ

2022-11-08 11:38 UTC, pocojang commented on src/js/service/ProductPurchaseService.js
> +  remainService() {
그르게요..
하지만 조금 더 리팩터링하면 더욱 아름다워질 것 같긴하군요 ㅎㅎ

2022-11-08 13:52 UTC, wondonghwi commented on src/js/service/ProductPurchaseService.js
> +    if (count > 0 && purchasePrice >= price) {
넵 수정했습니다~ 👍

2022-11-08 15:03 UTC, pocojang approved these changes
@wondonghwi 👋 
🎊 클린코드 완주를 축하드립니다 🎊 

일단 마지막으로 남겨주신 질답을 나눠볼게요

## Q1. 객체의 깊이에 대해서

현재 사용되는 객체의 깊이를 보면..
`this.stateData.twoDepth.threeDepth.fourDepth`로 이어지고 있답니다.
제가 드린 피드백의 요지는 깊이가 너무 깊어지니 관리가 어렵고 불안하다는 이야기였고 동휘님이 말씀하신 부분을 본다면 `로컬 스토리지 키`를 단일 키로 가지기 때문이다라고 말씀을 해주셨는데요.

그 부분에 공감이 어렵다는 이야기였습니다ㅎㅎ
마치 로컬 스토리지의 키와 애플리케이션의 키가 항상 일치해야만 FE 상태 관리에 어려움이 없다라는 이야기로 보였거든요.

`data-*`도 그렇고 `Local Storage` 사용도 그렇고 대부분의 상태를 브라우저에 잠시 담아놓는 것에 대한 방법을 채택하는 것이 지속적으로 눈에 보였고 미션을 학습하는 단계에서는 그러한 방법들은 잠시 지양해보고 오로지 상태에만 집중해보는게 어떨까? 제안을 드려보는 것이지요ㅎㅎ

돌아와서 다시 생각해보면 로컬 스토리지 키가 단 1개라면 프론트 앱의 상태가 복잡해지거나 깊이가 더 깊어지는게 자연스러울정도로 대등한 관계인지 생각해보셨으면 좋겠습니다!

그리고 Redux에서 복잡한 상태를 어떻게 [정규화](https://redux.js.org/usage/structuring-reducers/normalizing-state-shape)할 것인가에 대한 글이니 참고해보세요 :)

## Q2. let 임시 변수 사용


let을 꼭 사용하지 말아야할 이유가 없을 수 있지만 반대로 생각해보면 굳이 사용할 필요도 없다라고 말씀을 드리고 싶고요.
그렇다면 모든 로직에서 제거해보는 것도 고려해보시는 것은 어떨까요?
퍼포먼스 측면에서의 개선이 무의미하다면 차근차근 개선해보시는 것도 권해보고 싶습니다ㅎㅎ

설명보다는 간단한 [레퍼런스](https://github.com/qkraudghgh/clean-code-javascript-ko#%EB%AA%85%EB%A0%B9%ED%98%95-%ED%94%84%EB%A1%9C%EA%B7%B8%EB%9E%98%EB%B0%8D%EB%B3%B4%EB%8B%A4-%ED%95%A8%EC%88%98%ED%98%95-%ED%94%84%EB%A1%9C%EA%B7%B8%EB%9E%98%EB%B0%8D%EC%9D%84-%EC%A7%80%ED%96%A5%ED%95%98%EC%84%B8%EC%9A%94)가 더 좋겠죠?!

---

그럼 이만 머지하도록 하겠습니다
그동안 고생 많으셨습니다!

2022-11-08 15:03 UTC, merged