[클린코드 4기 유승완] 자판기 미션 STEP 1
next-step/js-vending-machine pull request #51
Opened 2022-12-12 21:14 UTC by Seung-wan

안녕하세요! 은규님! 
리뷰 잘부탁드립니다!
사소한 것들까지 언급해주시면 감사하겠습니다!

### 참고사항
요구사항에 `자판기가 보유한 금액 만큼의 동전이 무작위로 생성된다.`와 같은 내용이 있지만, 우선 500원, 100원, 50원, 10원 순서대로 생성되도록 구현하였습니다.

### 여쭤보고 싶은 부분
1. src/js/components/ProductManageMenu.js, src/js/components/VendingMachineManageMenu.js 파일에서 state에 관계 없이 일관되게 화면에 보여지는 부분은 `#getTemplate`으로 네이밍을 하였고 state에 따라 화면에 다르게 보여져야 하는 부분은 `#renderState`라고 이름을 지었습니다. 처음에는 `#getTemplate`에 모두 합치고 싶었지만, state가 바뀌게 되어 리렌더링을 하게 되면 이벤트 핸들러를 등록했던게 사라져서 나누게 되었는데요. 하나로 합치고 리렌더링 될때마다 이벤트 핸들러를 다시 등록해줘도 되는걸까요? 아니면 조금 더 효율적으로 작성할 수 있는 방식으로 어떻게 생각해보는게 좋을지 여쭤보고 싶습니다.

2. src/js/components/VendingMachineManageMenu.js 파일의 상단에 상수를 선언하였습니다. 이런 상수들은 src/js/constants 폴더 아래에 따로 작성해주는게 괜찮을까요? 아니면 상수가 쓰이는 파일에 위치시켜도 괜찮을까요?

2022-12-13 20:59 UTC, EungyuCho reviewed
목요일 새벽쯤에 추가로 코멘트 달아서 변경 요청드릴게요 🙇‍♂️

2022-12-13 20:59 UTC, EungyuCho commented on src/js/utils/validation.js
> +const isEmpty = (input) => input === '';
`isEmpty`만 함수로 만드는 것 보다 `validate` 함수에서 첫번째 인자로 넣어주는 `predicate`인자에 공통 정책으로 분리할만하다면 `validator`를 만들어보는것도 좋을 것 같아요.
e.g.
```javascript
const validator = {
  isEmpty: (value) => value === '',
  // lt lte gt gte 등 일반적으로 축약형이 있다면 사용해도 좋아요
  largeThan: (baseValue, compareValue) => baseValue > compareValue,
  // 등등...
}
```

2022-12-13 20:59 UTC, EungyuCho commented on src/js/components/ProductManageMenu.js
> +      validateProductQuantity(quantity);
검증하기전에 타입을 변경해주는게 나을 것 같아요 👀 
`<input type='number' />`의 경우 valueAsNumber를 사용해도 안전하다고 생각해요
```suggestion
      const price = $(SELECTOR.PRODUCT_PRICE_INPUT).valueAsNumber;
      validateProductPrice(price);

      const quantity = $(SELECTOR.PRODUCT_QUANTITY_INPUT).valueAsNumber;
      validateProductQuantity(quantity);
```

2022-12-13 20:59 UTC, EungyuCho commented on src/js/components/ProductManageMenu.js
> +    const isNotExist = targetIndex === -1;
`targetIndex`라는 변수로 분리하는데 크게 의미가 있지는 않을 것 같아서 두 줄로 분리하는 이득이 딱히 없어보여요 🤔 
```suggestion
    const currentProductNotStored = this.#state.products.findIndex((stateProduct) => stateProduct.name === product.name) === -1;
```

2022-12-13 20:59 UTC, EungyuCho commented on src/js/components/VendingMachineManageMenu.js
> +      alert(error.message);
의도치 않은 에러 메세지를 띄워주지 않기 위해 custom Error를 활용할 수 있을거같아요 👀 
[참고](https://github.com/next-step/js-lotto/pull/203/commits/0c301b3efad51004a74c08affb20aeffcb356f0b)

2022-12-14 19:54 UTC, Seung-wan commented on src/js/utils/validation.js
> +const isEmpty = (input) => input === '';
`~와 같다`, `~보다 작다`,` ~보다 크다` 이런 조건들을 분리할까 말까 고민을 했었는데 분리해도 좋다는 생각이 들었고, 
분리를 한다면 말씀해주신 것처럼`validator`라는 객체를 만들어서 내부에 작성하는 방식도 좋은 것 같습니다!

2022-12-14 19:56 UTC, Seung-wan commented on src/js/components/ProductManageMenu.js
> +      validateProductQuantity(quantity);
저도 검증하기전에 형변환을 해주는 것이 좋을 것 같습니다. 
지금의 경우에는 문자열인 상태로 검증을 하고 있는데 자동 형변환이 되는 연산자를 이용하여 검증이 되어서 별 문제가 없었던 것 같네요.
또한 `<input type='number' />`이기 때문에 valueAsNumber를 사용하는 것이 좋다고 생각됩니다!

2022-12-14 19:58 UTC, Seung-wan commented on src/js/components/ProductManageMenu.js
> +    const isNotExist = targetIndex === -1;
코드를 다시 보니까 저도 똑같은 느낌이 드는 것 같습니다.
오히려 한 줄로 처리하는 게 훨씬 괜찮아 보입니다!

2022-12-14 19:59 UTC, Seung-wan commented on src/js/components/VendingMachineManageMenu.js
> +      alert(error.message);
에러 처리를 조금 더 세련되게 해봐야겠습니다.
반영해보겠습니다!

2022-12-14 19:59 UTC, EungyuCho requested changes
안녕하세요 승완님! 마지막 미션 잘 부탁드립니다 :)

### 질문사항
1.  리렌더링 될때마다 이벤트 핸들러를 다시 등록해줘도 되는걸까요? 아니면 조금 더 효율적으로 작성할 수 있는 방식으로 어떻게 생각해보는게 좋을지 여쭤보고 싶습니다.

불필요하게 브라우저 자원을 소비하는게 좋진 않다고 생각해요 👀 
이벤트 위임을 통해 해결해볼수도 있을 것 같고 말씀해주신대로 함수를 통합해서 매번 재등록하는 방법도 있을 것 같아요.

2. src/js/components/VendingMachineManageMenu.js 파일의 상단에 상수를 선언하였습니다. 이런 상수들은 src/js/constants 폴더 아래에 따로 작성해주는게 괜찮을까요? 아니면 상수가 쓰이는 파일에 위치시켜도 괜찮을까요?

재사용할 여지가 없다면 해당 파일에 둬도 크게 문제가 되진 않을 것 같아요.
다만 깔끔하게 작성하고 싶다면 components/VendingMachineManageMenu/constants.js에 정의해둘 것 같아요.

도메인별로 공유해서 사용할 여지가 있을때에는 공통적인 상수 폴더로 분리하거나 공유되는 도메인별 모듈폴더를 만들어서 상수를 선언할 것 같아요.

한번 코멘트들 보시고 다시 리뷰요청 부탁드릴게요! 🙏

2022-12-14 19:59 UTC, EungyuCho commented on cypress/support/commands.js
> +
(사소) 액션이나 도메인에 따라 커맨드를 [addAll](https://docs.cypress.io/api/cypress-api/custom-commands#Usage)로 분리해서 정리해두면 깔끔하기도하고 관심사끼리 뭉쳐둘 수 있어 좋을 것 같아요

2022-12-14 19:59 UTC, EungyuCho commented on src/js/App.js
> +    }
suggestion도 없어서 문자열로 관리하다보면 실수할 여지가 있을 것 같은데 id로 가져오지 않는건 어떨까요?
button element의 [dataset](https://developer.mozilla.org/ko/docs/Learn/HTML/Howto/Use_data_attributes)에 category를 적어보는것도 좋을 것 같아요.

2022-12-14 19:59 UTC, EungyuCho commented on src/js/components/VendingMachineManageMenu.js
> +    localStorage.setItem('charge', String(this.#state.charge));
스토리지관련 유틸을 추가해봐도 좋을 것 같아요.
아니면 자판기에 필요한 상태를 어떤 형식으로 저장하고 파싱해야하는지 온전히 맡겨도 깔끔해질 것 같기도하구요 🤔

2022-12-14 19:59 UTC, EungyuCho commented on cypress/e2e/vendingMachine.cy.js
> +      });
```suggestion
      const stub = getAlertStub();
      
      cy.typeProductPrice(1000);
      cy.typeProductQuantity(5);

      cy.clickProductAddButton().then(() => {
        stub.calledWith(ERROR_MESSAGE.EMPTY_INPUT);
      });
```
이런 인터페이스로 함수가 작성되면 편할 것 같아요 👀

2022-12-14 19:59 UTC, EungyuCho commented on src/js/components/ProductManageMenu.js
> +      const name = $(SELECTOR.PRODUCT_NAME_INPUT).value;
(마이너) 클릭 이벤트마다 `PRODUCT_NAME_INPUT`를 query selector로 가져오고 있는데 클래스의 필드로 가지고 있었다면 어땠을까요?

2022-12-14 19:59 UTC, EungyuCho commented on src/js/components/ProductManageMenu.js
> +    this.#state.products.splice(targetIndex, 1, product);
조금 더 좋은 방법이 없을까요?
새로 상품을 갱신해주기위한 점을 바로 인식하기 어려울수도 있다고 생각해요 

상품을 Array가 아닌 Map으로 관리하면 보다 효율적인 탐색과 읽기 편한 인터페이스가 나올 것 같다는 생각이 들었어요

2022-12-14 19:59 UTC, EungyuCho commented on src/js/components/VendingMachineManageMenu.js
> +    localStorage.setItem('charge', String(this.#state.charge));
아니면 coin - product등 각각의 클래스로 분리해서 관리해도 좋을 것 같습니다

2022-12-14 20:12 UTC, Seung-wan commented on cypress/support/commands.js
> +
addAll을 이용해서 응집시킬 수 있었군요!
활용해보겠습니다!

2022-12-14 20:14 UTC, Seung-wan commented on src/js/App.js
> +    }
확실히 사람이 순수 타이핑을 해야하는 문자열은 실수할 여지가 있을 것 같습니다. 
dataset attribute와 같은 다른 방안으로 작성해보겠습니다!

2022-12-14 20:15 UTC, Seung-wan commented on src/js/components/VendingMachineManageMenu.js
> +    localStorage.setItem('charge', String(this.#state.charge));
확실히 localStorage를 그대로 사용하기 보다는 한번 래핑해서 깔끔하게 사용해보는게 좋은 선택일 것 같습니다!
반영해보겠습니다!

2022-12-14 20:15 UTC, Seung-wan commented on cypress/e2e/vendingMachine.cy.js
> +      });
훨씬 깔끔하고 편하니 좋네요!
수정해보겠습니다!

2022-12-14 20:18 UTC, Seung-wan commented on src/js/components/ProductManageMenu.js
> +    this.#state.products.splice(targetIndex, 1, product);
확실히 splice는 잘 쓰지 않기도 하고 저도 오랜만에 써보려니 매개변수 순서가 기억이 안나서 찾아보고 썼었네요.
데이터를 어떤 자료구조에 담는 것이 가장 효율적일지 결정하는 과정이 은근 고민이 됐던 것 같습니다.
Map으로 관리하게 되면 확실히 성능적으로 효율적이고, 가독성이 향상될 것이라 생각이 됩니다!

2022-12-14 20:22 UTC, Seung-wan commented on src/js/components/ProductManageMenu.js
> +      const name = $(SELECTOR.PRODUCT_NAME_INPUT).value;
확실히 클릭 이벤트마다 DOM에 계속 접근하는 것 보다는 상태값처럼 `PRODUCT_NAME`을 컴포넌트에서 관리하고 있다면 좋을 것 같습니다.  input, change 같은 event를 한번 활용해보도록 하겠습니다!

2022-12-15 21:50 UTC, Seung-wan commented
폴더 구조를 깔끔하게 작성하는 것은 생각이 많이 필요할 것 같고 저만의 기준을 세워나가는 것도 중요하다는 생각이 많이 들었습니다.
또한, 항상 더 좋은 코드를 작성할 수 있을지 깊이 고민하는 시간을 갖는 것이 중요한 것 같습니다.
리뷰 주신 내용들 생각하고 반영해보았습니다!

2022-12-18 06:48 UTC, EungyuCho commented on src/js/components/ProductManageMenu/ProductManageMenu.js
> +      }
`InvalidValueError`와 `EmptyInputError`가 모두 별도로 `CustomError`를 상속받으면 이렇게도 가능할 것 같아요
```suggestion
      if (error instanceof CusttomError) {
        alert(error.message);
      }
```

2022-12-18 07:12 UTC, EungyuCho commented on cypress/e2e/vendingMachine.cy.js
> +      });
최소 가격이 100원이면 테스트용으로 사용하는 데이터도 100원으로 설정해서 경계값테스트를 하는게 좋아요~

2022-12-18 07:25 UTC, EungyuCho commented on cypress/e2e/vendingMachine.cy.js
> +          expect(Number($el.children()[PRODUCT_INDEX.QUANTITY].textContent)).to.equal(products[idx].quantity);
```suggestion
          const { name, price, quantity } = products[idx];
          expect($el.children()[PRODUCT_INDEX.NAME].textContent).to.equal(name);
          expect(Number($el.children()[PRODUCT_INDEX.PRICE].textContent)).to.equal(price);
          expect(Number($el.children()[PRODUCT_INDEX.QUANTITY].textContent)).to.equal(quantity);
```
(마이너) 줄일 수 있는건 줄여봅시당 ㅎ.ㅎ

2022-12-18 07:25 UTC, EungyuCho commented on src/js/utils/storage.js
> +};
이거 key는 달라지지 않지 않나용?..

2022-12-18 07:34 UTC, EungyuCho commented on cypress/e2e/vendingMachine.cy.js
> +      });
요것은 혹시 시도했는데 잘 안되셨을까요? 👀

2022-12-18 07:45 UTC, EungyuCho requested changes
승완님 안녕하세요 ㅎㅎ

전체적으로 제가 생각한 방향으로 개선이 많이 된 것 같아요.
제안드린 내용중에 해결하지 못한 부분도 있는데 혹시나 구현하는데 어려움이 있다면 편하게 말씀해주세요 :)

추가적으로 코멘트도 남겨드렸는데 한번 확인 부탁드립니다~

2022-12-18 12:01 UTC, Seung-wan commented on src/js/components/ProductManageMenu/ProductManageMenu.js
> +      }
instanceof가 프로토타입 체인을 타고 올라가면서 확인을 하는데 
최상위엔 CustomError 클래스의 프로토타입이 있을테니 훨씬 깔끔하니 좋은 것 같습니다!

2022-12-18 12:30 UTC, Seung-wan commented on cypress/e2e/vendingMachine.cy.js
> +      });
체크해주셔서 감사합니다!
요구사항에 최대한 적합한 테스트를 작성하는 데 있어서 데이터도 신경써서 진행해야 될 것 같습니다!

2022-12-18 12:37 UTC, Seung-wan commented on cypress/e2e/vendingMachine.cy.js
> +          expect(Number($el.children()[PRODUCT_INDEX.QUANTITY].textContent)).to.equal(products[idx].quantity);
저도 이러한 경우에 구조분해할당으로 객체에서 필요한 값들만 사용하는 방식을 좋아하는데 여기선 놓쳐버린 것 같습니다.
평소에도 객체에 접근하는 경우에는 스스로 한번 확인하거나 린트에서 잡아줬었는데 방심해버렸네요.
확인해주셔서 감사합니다!

2022-12-18 12:58 UTC, Seung-wan commented on src/js/utils/storage.js
> +};
![image](https://user-images.githubusercontent.com/51105841/208299275-f10a7b34-e6b1-4872-929e-0117f15f58a3.png)

헛! 남겨주신 코멘트보고 생각해보니 띵! 했네요.
만약 포괄적으로 쓰일 수 있는 `storage`였다면 `key`를 받아야 되겠지만, 도메인에 종속적인 `storage`로 작성되어 있기 때문에 `key`를 받을 필요가 없을 것 같습니다. key`를` 상수화하여 명시적으로 작성해주는게 훨씬 괜찮을 것 같습니다.

근데 생각해보니 `utils/storage.js`에 작성되어 있는 storage들은` localStorage.getItem`, `localStorage.setItem` 메소드들을 사용하는 과정에서 도메인 로직이 조금 묻어있다는 생각이 드는데 `utils`에 포함시켜도 괜찮다고 볼 수 있을까요?
아니면 `utils`가 아닌 컴포넌트 내부라던가 다른 곳에 작성하는게 괜찮을까요?

2022-12-18 13:01 UTC, Seung-wan commented
안녕하세요 은규님!!
자판기 잔돈충전시 동전이 무작위로 생성되는 로직과 테스트코드는 STEP2에서 추가하여 작성해보겠습니다!

추가로 아래 리뷰 남겨주신 부분에 추가로 궁금증이 있어서 질문을 드렸는데 확인 부탁드립니다!
https://github.com/next-step/js-vending-machine/pull/51#discussion_r1051545023

2022-12-18 16:45 UTC, EungyuCho commented on src/js/utils/storage.js
> +};
설정하기 나름이긴한데 utils에 두는게 좋아보여요.

최상위 폴더 구조를 도메인 기준으로 나눴으면 말씀하신대로 도메인쪽 폴더에 포함을 시켜도 되었을 것 같은데.. 지금은 아닌 것 같아요
도메인 로직이 묻어있는게 조금 거슬리신다면 `utils/storage/product.js`처럼 depth를 하나 더 두는것도 방법일 것 같아요

2022-12-18 17:10 UTC, EungyuCho approved these changes
고생하셨습니다 승완님 ㅎㅎ
질문주신 부분이랑 추가적으로 고쳐보면 좋을 코드들을 발견해서 suggestion을 드렸는데요~ 피드백을 반영하신다면 다음 step2에서 포함시켜주시면 되겠습니다~!

승완님의 피드백 반영속도가 엄청나네요 😮 
빠른 속도로 미션 진행해주시고 피드백 드린 부분들도 찰떡같이 반영해주셔서 좋았습니다 코드도 전체적으로 간결했어요~
approve후에도 궁금증이 생기시면 리뷰 요청 전이라도 추가적으로 코멘트나 슬랙에 여쭤봐주세요!

고생하셨어요 승완님 👏

2022-12-18 17:10 UTC, EungyuCho commented on src/js/components/VendingMachineManageMenu/VendingMachineManageMenu.js
> +    });
```suggestion
    const { coins } = units.reduce((prev, acc) => {
        const currentCoin = Math.floor(prev.charge / acc);
        const newCoins = { ...prev.coins, [acc]: currentCoin };
        const remainCharge = prev.charge - currentCoin * acc;
        
        return { coins: newCoins, charge: remainCharge }
    }, { coins: {}, charge })
```
성능적으로 더 좋지는 않겠지만 이렇게 작성하면 lint룰도 회피할 수 있고 동작도 예측하기 수월할거라고 생각해요 👀

2022-12-18 17:10 UTC, EungyuCho commented on src/js/components/ProductManageMenu/ProductManageMenu.js
> +      validateProductQuantity(quantity);
(사소) 개행을 하시는 기준이 있을까요? 👀 

전부 validation을 하는 메서드들이라 개행을 하지 않는편이 더 이해하기 쉬울 것 같아서요!

2022-12-18 17:10 UTC, EungyuCho commented on src/js/components/VendingMachineManageMenu/VendingMachineManageMenu.js
> +  }
spread해서 반환해주는게 좋을 것 같아요.
this.#state는 주소값을 참조하고 있어서.. 호출하는 쪽에서 private 필드인 state의 값을 조작할 수 있어요

2022-12-18 17:11 UTC, merged

2022-12-18 19:19 UTC, Seung-wan commented on src/js/utils/storage.js
> +};
depth를 하나 두면 도메인별로 분리를 할 수는 있겠네요! 다양한 접근법을 얻어가고 있는 것 같아서 좋습니다
저는 우선은 그대로 둬도 괜찮을 것 같습니다!

2022-12-18 19:38 UTC, Seung-wan commented on src/js/components/VendingMachineManageMenu/VendingMachineManageMenu.js
> +    });
`이 부분 로직을 어떻게 작성하는게 효과적일까?`라고 고민을 했었는데 확실히 동작을 예측하기에 좋아진 것 같습니다.
배열을 `forEach`를 돌릴거라면, `reduce`를 먼저 고민해봤어도 좋았을 거라는 생각도 드네요.

`remainCharge`를 구하는 로직이 직관적인게 마음에 듭니다. 제안 감사합니다!

2022-12-18 19:45 UTC, Seung-wan commented on src/js/components/ProductManageMenu/ProductManageMenu.js
> +      validateProductQuantity(quantity);
작성했을 당시에는 뭔가 `validation하는 행위들이니까 각각 좀 의미있게 개행해볼까?` 라는 의도로 했지 않을까 싶은데
의미없이 개행을 했던 것 같고 지금 보니까 오히려 가독성을 해치고 있는 것 같습니다.
validation끼리 뭉쳐주는게 좋은 것 같습니다!

2022-12-18 20:03 UTC, Seung-wan commented on src/js/components/VendingMachineManageMenu/VendingMachineManageMenu.js
> +  }
`state`가 `reference type`이면 이런 주의할점이 있군요!
확인 감사합니다!