[클린코드 4기 최호중] 자판기 미션 STEP 2
next-step/js-vending-machine pull request #56
Opened 2022-12-26 09:15 UTC by sannimdev

안녕하세요 리뷰어님!
NextStep 클린코드 과정에서 마지막 결실을 위해 성탄 연휴 약속까지 반납하고 자판기 미션을 이어갔습니다.
생각보다 자판기 미션에 들어가는 코드가 복잡하고 볼 구석이 많다는 느낌이 들었습니다.
그런데 이번에 웹 컴포넌트 미션이 새롭게 추가되면서 리뷰어님께서도 살펴보셔야 할 부분이 늘어난 것 같아요.
STEP1에서 나눴던 대화(conversation)의 댓글이 100건이 넘어가던데 리뷰어님께서 마치 당신의 코드처럼 하나씩 살펴봐 주셨다는 것이 너무도 감사할 따름입니다. 시간과 에너지를 쏟아주시면서 세밀한 부분 살펴봐 주셔서 진심으로 감사했습니다.

이번 STEP2에서는
1. 웹 컴포넌트 마이그레이션 작업
2. 자판기 구매 기능 작업 

위 2가지를 진행하는 미션입니다.

## 이건 다음에 고민해볼게요!

위와 별개로 지난 PR에서 리뷰어님께서 좋은 제안을 주셨지만, 다 반영하기에는 물리적인 시간의 제약으로 인해 반영하지 못하게 된 부분이 있어 양해의 말씀을 드리고자 합니다.
- 네이밍 일관성 (changes쪽.. 고민하면서 고쳐볼게요)
- js코드가 HTML DOM 구조를 의존하는 것보다는 반대의 의존성이 더 좋다고 하시는 의견
  - 이 부분과 관련해서는 코드를 다 뜯어고치기에는 무리가 있어 보여요. 제가 다른 곳에서 리뷰어님의 제안을 곰곰이 생각해보면서 두 가지의 차이점에 관해 살펴보도록 하겠습니다.
- Custom Error의 다양화
  - 이번 STEP2를 진행하면서 리뷰어님께서 제안해주신 대로 여러 가지 Error의 유형으로 세분화하고 싶더라구요! 하지만, 참았습니다. ㅠㅠ 이것까지 고민하기에는 제 에너지가 모자랍니다. 양해 부탁드려요.
 

## STEP2에서 진행한 부분

1. 웹 컴포넌트
    - 웹 컴포넌트가 무엇이고 왜 등장했고 어떻게 사용하는지 정도만 개인적인 학습 목표로 잡기로 했어요.
    - 어떻게 더 효율적으로 쓸 건지, 어떻게 하면 더 컴포넌트화하여 잘 뽑아낼 수 있는지에 관해서까지는 피드백 주신다면 남은 시간 동안 좀 더 곰곰이 생각해보겠습니다!
    - 테스트에서 어떻게 shadowDom을 테스트하는지에 관해 학습했어요
2. 자판기 구매 기능

PR 요청이 1/1까지라고 들었어요!
그래서 조금 아쉬운 부분이 스스로도 보이지만, 리뷰어님의 인사이트를 조금이라도 더 얻으려면 빨리 올려서 조금의 피드백이라도 반영하는 쪽이 좋을 것 같다고 생각했어요.

리뷰어님께서도 일정이 있으시고 아무래도 연말이다 보니까 피드백 주시는 부분에 대해 많은 것들을 반영하지는 못할 것 같아서 죄송함이 앞섭니다ㅠㅠ. 하지만, 이번 미션 진행기간이 지나더라도 리뷰어님께서 가볍게 툭 툭 던져주시는 메시지 하나 하나도 곰곰이 고민해보도록 하겠습니다. 정말 고생 많으셨습니다 리뷰어님!

2022-12-26 09:16 UTC, sannimdev commented
git 충돌 작업.. 저녁 먹고 다시 와서 작업할게요 ㅠㅠ

2022-12-27 14:36 UTC, JunilHwang requested changes
안녕하세요 호중님!
연말임에도 불구하고 열정적으로 미션을 수행해주셨네요 👏👏👏

일단 네이밍을 조금 더 디테일하게 신경써주시면 좋을 것 같아요

가령,
- 자판기(VendingMachine)와 다시 그리기 (redraw)는 어떤 관계가 있는걸까요?
- 자판기(VendingMachine)과 제품 관리자(ProductManager)라는 관계는 어색한 것 같아요
  - 자판기와 자판기 상품(VendingProduct) 처럼 표현해보는 연습을 해보세요! "코드"의 입장이 아닌 "도메인"의 입장에서 코드를 작성해야합니다.

지금은 "코드의 입장"으로 이름을 지은 것들이 많은데, 이럴 경우 내가 무엇을 표현하고자 하는지가 애매해집니다.
어디선가는 도메인을 표현하고 있고, 어디선가는 도메인 외적인걸 표현하고 있으니까요!

그리고 지금 렌더링에 대한 이슈가 조금 있는 것 같아요. 어색하다고 해야하나..
웹 컴포넌트 자체의 문제 + 렌더링 타이밍 문제 가 있는 것 같습니다.
이 부분도 개선해주시면 완벽해질 것 같아요!

공식적인 과정은 1월 1일까지지만, 호중님이 피드백 요청을 보내주시면 언제든 리뷰할테니 급하게 하지 않아도 된답니다 ㅎㅎ

조금만 더 힘내봅시다!! 화이팅 💪💪

2022-12-27 14:36 UTC, JunilHwang commented on src/js/util/object.js
> +      }
Array일 때는 cloneDeepArray를 씌워줘야하지 않을까요!?

2022-12-27 14:36 UTC, JunilHwang commented on src/js/util/object.js
> +    }, {})
```suggestion
    keys.reduce((result, key) => {
      const value = object[key];
      const copiedValue = Array.isArray(value)      ? cloneDeepArray(value)  :
                          typeof value === 'object' ? cloneDeepObject(value) :  value;
                                          
      return { ...result, [key]: value };
    }, {});
```
이럴 때는 중첩 삼항연산자를 사용해도 깔끔할 것 같아요!
다만 prettier ignore가 필요하겠네요 ㅋㅋ

2022-12-27 14:36 UTC, JunilHwang commented on src/js/util/object.js
> +}
```suggestion
function cloneDeepObject(object) {
  return Object.entries(object)
            .reduce((result, [key, value]) => ({
              ...result, [key]: cloneDeep(value)
            }), {});
}

function cloneDeepArray(array) {
  return array.map(cloneDeep);
}
```
생각해보니, 이렇게 표현해도 되겠네요 ㅎㅎ

2022-12-27 14:36 UTC, JunilHwang commented on src/js/util/object.js
> +}
```suggestion
function cloneDeepObject(object) {
  return Object.entries(object)
            .reduce((result, [key, value]) => ({
              ...result,
              [key]: cloneDeep(value)
            }), {});
}

function cloneDeepArray(array) {
  return array.map(cloneDeep);
}
```
생각해보니, 이렇게 표현해도 되겠네요 ㅎㅎ

2022-12-27 14:36 UTC, JunilHwang commented on index.html
> +          ></smart-table>
https://user-images.githubusercontent.com/18749057/209675543-fc9069d3-8591-46f5-a382-50beca24f4ec.mov

button도 그렇고,
table도 그렇고,
이렇게 두 번 렌더링이 되어야 정상적으로 보여집니다.
최초에 한 번 렌더링 될 때 정상적인 모습으로 보여지도록 하려면 어떻게 해야좋을까요!?

2022-12-27 14:36 UTC, JunilHwang commented on index.html
> +    <script type="module" src="./src/js/component/smart-table.js"></script>
index에서 컴포넌트를 import 해도 무방할 것 같아요!

2022-12-27 14:36 UTC, JunilHwang commented on src/js/component/smart-table.js
> +    this._shadowRoot.appendChild(template.content.cloneNode(true));
clone 후에 h2를 미리 채워주면 어떨까요?

2022-12-27 14:36 UTC, JunilHwang commented on src/js/component/styled-button.js
> +<button class="btn btn-secondary"><slot></slot></button>
이 button에 대한 class를 미리 style에 정의해두면 어떨까요?
style도 같이 묶어줘야 컴포넌트로 사용하는 의미가 있을 것 같아요!

2022-12-27 14:36 UTC, JunilHwang commented on src/js/service/VendingMachine.js
> +  #insertedMoney;
VendingMacine에 대한 상수는 아예 이 class에 정의해주면 어떨까요?
```js
class VendingMachine {
  static MIN_AMOUNT = 10;
  static MULTIPLE = 10;

  /* 생략 /*
}
```
이럴 경우 `VendingMachine.MIN_AMOUNT` 처럼 사용할 수 있답니다 ㅎㅎ

2022-12-27 14:36 UTC, JunilHwang commented on src/js/service/constant.js
> +  },
앞선 내용을 참고해본다면, 각각의 class에 상수를 정의해줄 수 있지 않을까요?

2022-12-27 14:36 UTC, JunilHwang commented on src/js/service/VendingMachine.js
>    }
```js
  constructor(products, unitCountInfo) {
    this.#productManager = products;
    this.#unitCountMachine = unitCountInfo;
    this.#insertedMoney = 0;
  }
```
products와 unitCountInfo가 이미 instance인 상태로 들어올 수도 있지 않을까요!?

혹은 한 가지로 제한하고 싶다면, 검증 과정이 필요하지 않을까요?

참고로

다양한 타입을 받아서 사용한다 = 다형성

이라고 보시면 좋을 것 같습니다!

2022-12-27 14:36 UTC, JunilHwang commented on src/js/service/VendingMachine.js
> +    if (!(product && this.#insertedMoney - product.price >= 0)) {
```suggestion
    if (!product || this.#insertedMoney < product.price) {
```
저는 개인적으로 이렇게 표현하는게 더 명확하다고 생각해요!

지금은
- 조건문을 이해해야 하고 ( 제품이 있어야 하고, 자판기에 들어온 돈이 제품의 가격보다 커야 함)
  - 가격 비교도 단순 비교가 아니라 연산 후에 0보다 큰지 봐야하네요.. ㅎㅎ
- 해당 조건의 반대되는 경우 또한 이해해야합니다.

그래서 제안해드린 코드로 변경할 경우
- 제품이 없거나
- 제품 가격보다 작거나

이럴 경우 코드를 이해하는 비용이 더 적어지지 않나요!?

2022-12-27 14:36 UTC, JunilHwang commented on src/js/service/VendingMachine.js
> +    isInteger(amount) && isGreaterThan(amount, MIN_AMOUNT) && isMultipleOf(amount, MULTIPLE);
```suggestion
  insertMoney(amount) {
    !VendingMachine.#validateInsertedMoney(amount));
    this.#insertedMoney += amount;
  }

  returnChanges() {
    const { amount, unitInfo } = this.#unitCountMachine.redraw(this.#insertedMoney);
    this.#insertedMoney -= amount;
    return { amount, unitInfo };
  }

  static #validateInsertedMoney(amount) {
    if(isInteger(amount) && isGreaterThan(amount, MIN_AMOUNT) && isMultipleOf(amount, MULTIPLE)) {
      throw new ValidationError(ERROR_MESSAGE.VALIDATION.SPENDING_MONEY_INPUT)
    }
  }
```

현재 상태는 검증에 대한 책임을 insertMoeny와 isInsertedMoneyValid가 나눠가진 상태입니다.
이걸 제시한 것 처럼 아예 한 곳에 몰아주면 어떨까요!?

2022-12-27 14:36 UTC, JunilHwang commented on src/js/service/VendingMachine.js
> +  }
changes는... 정말 적합한 네이밍이 아닌 것 같아요
표현하기 어렵다면 차라리 한글 변수를 쓰는 것도 좋은 방법이랍니다 ㅎㅎ

2022-12-27 14:36 UTC, JunilHwang commented on src/js/service/ProductManager.js
> +export default class ProductManager {
매니저와 자판기는 어울리지 않는 단어라고 생각해요.

차라리

- VendingProduct
- VendingProducts

이렇게 두 가지로 분산해서 표현해보면 어떨까요?

- 현재: 자판기 - 상품 관리자
- 개선: 자판기 - 자판기 상품

어떤게 더 현재 도메인을 기준으로 명확한 관계를 표현하는 것 같나요!?

2022-12-27 14:36 UTC, JunilHwang commented on src/js/service/ProductManager.js
> +  }
products에서 product를 검증하네요

앞서 제안해드린 것 처럼 VendingProduct라는 class를 하나 더 만들고, 이 부분을 위임해주면 어떨까요?

- 자판기(VendingMachine) - 자판기 상품들(VendingProducts) - 자판기 상품(VendingProduct)

이런 구조랍니다!

2022-12-27 14:36 UTC, JunilHwang commented on src/js/service/UnitCountMachine.js
> +  }
자판기 상품 쪽에도 그렇고, redraw라는 메소드를 사용 중인데

"자판기" 라는 도메인에 "다시 그리다" 라는 용어 자체가 어색하지 않을까요!?
더 적합한 표형 방법이 있으리라 생각합니다!

2022-12-27 14:36 UTC, JunilHwang commented on src/js/ui/constant.js
> +};
1안
```js
// Storage는 localStorage관리하는 class로, 적절하게 정의되었다고 가정

const productRepository = new Storage('products');
const unitCountsRepository = new Storage('unit_counts');
```

2안
```js
// Storage는 localStorage관리하는 class로, 적절하게 정의되었다고 가정
class ProductStorage extends Storage {
  constructor() {
    super('products')
  }
}

class UnitCountStorage extends Storage {
  constructor() {
    super('unit_counts')
  }
}


const productRepository = new ProductStorage();
const unitCountsRepository = new UnitCountStorage();
```

이렇게 쓰인다면 상수의 사용 비율이 매우 줄어들지 않을까요? 아예 상수를 정의를 하지 않아도 사용할 수 있겠네요 ㅎㅎ

2022-12-27 14:36 UTC, JunilHwang commented on src/js/util/dataSaver.js
> +}
앞선 리뷰를 토대로 이 부분을 개선해보면 어떨까요?

2022-12-27 14:36 UTC, JunilHwang commented on src/js/util/dataSaver.js
> +}
그리고 이 함수들이 유틸 함수가 맞을까요?

2022-12-29 07:26 UTC, crontable commented on src/js/service/VendingMachine.js
> +  #insertedMoney;
VendingMachine에 관한 상수는 클래스에 정보가 있으면 명확하지만,
[이전에 해주신 조언에 따라](https://github.com/next-step/js-vending-machine/pull/50#discussion_r1052296212) 웬만해서는 클래스에서 변경되어서는 안 되는 정보는 읽기전용으로 만들고자 했습니다.

물론, 이 프로젝트는 저 혼자 사용하는 것이고 상식적으로도 static으로 선언했지만 이 값을 누군가가 혹은 프로그램에 의해 예기치 않게 값이 바뀔 경우가 있다고 생각하여 별도의 파일에서 불가피하게 상수화하였습니다.

2022-12-29 07:26 UTC, crontable commented on src/js/service/constant.js
> +  },
https://github.com/next-step/js-vending-machine/pull/50#discussion_r1052296212 웬만해서는 클래스에서 변경되어서는 안 되는 정보는 읽기전용으로 만들고자 했습니다.

물론, 이 프로젝트는 저 혼자 사용하는 것이고 상식적으로도 static으로 선언했지만 이 값을 누군가가 혹은 프로그램에 의해 예기치 않게 값이 바뀔 경우가 있다고 생각하여 별도의 파일에서 불가피하게 상수화하였습니다.

다만, 프로그램의 규모가 커지고 프로젝트가 복잡해진다면 이 부분에 관해서 고민해 볼 필요가 있겠네요!

2022-12-29 07:34 UTC, crontable commented on src/js/service/VendingMachine.js
>    }
넵 맞습니다. products, unitCountInfo는 자바스크립트 특성상 다양한 유형으로 들어올 수 있습니다.
그래서 각각 올바른 유형으로 유입되었는지 확인하는 방어 코드가 준비되어 있습니다!

2022-12-29 07:35 UTC, crontable commented on src/js/service/VendingMachine.js
> +    if (!(product && this.#insertedMoney - product.price >= 0)) {
코드를 이해하는 비용에 관해서도 여러 모로 고민이 필요한 부분이군요!

2022-12-29 07:39 UTC, crontable commented on src/js/service/VendingMachine.js
> +  }
`거스름돈`을 반환한다는 의미를 표현하려고 해서 찾은 단어여서 [changes](https://en.dict.naver.com/#/entry/enko/11f8ebca94974f2aa361ed6079309404)를 사용했습니다. 적합하지 않다고 생각하신 이유에 관해서 구체적으로 이야기를 들어볼 수 있을까요?

2022-12-29 07:55 UTC, crontable commented on src/js/util/object.js
> +    }, {})
제안해주신 부분을 중첩 삼항연산자를 적용하는 데는 조금 무리가 있어 보입니다.
되도록이면 일관성을 지키고 예외 케이스를 최소화하고자 합니다.

1. prettier ignore를 위한 예외 케이스를 작성하는 것도 개인적으로는 꺼림칙합니다.
2. airbnb의 코드 스타일 가이드를 지향하고 있어서 중첩 삼항연산자는 지양하고자 합니다.
> [15.6](https://github.com/airbnb/javascript#comparison--nested-ternaries) Ternaries should not be nested and generally be single line expressions. eslint: [no-nested-ternary](https://eslint.org/docs/rules/no-nested-ternary)

가독성 vs 명확성으로 팽팽하게 대립하는데 이 부분에 관해서는 개인적인 호불호가 갈리는 부분이어서 일관성을 가져가는 쪽으로 진행할게요! 새로운 관점을 제시해주셔서 감사합니다

2022-12-29 07:57 UTC, crontable commented on src/js/util/object.js
> +}
부연 설명을 해드리자면, get 메서드를 이용해서 객체를 취득하면 해당 객체의 쓰기도 엄격히 금지시키고 싶은 의도가 섞여 있었습니다. 그래서 객체의 키에 해당하는 값이 'object'인 경우 Object.freeze를 사용해서 객체의 변경을 방어할 의도가 있었습니다. 제안해주신 코드가 명확하고 깔끔해보이지만, 검증을 위해 불가피하게 코드가 추가된 점에 관해서 말씀드리고자 합니다. 이 부분 관련해서는 복사만 하는 것이 아니니 메서드의 이름에 readOnly를 추가하도록 할게요!

또한, 이번 프로젝트에서는 객체를 복사해서 재사용할 의도는 없으므로 시간관계상 읽기전용만 가능한 복사된 객체를 만드는 함수로 작성하겠습니다.

2022-12-29 08:26 UTC, crontable commented on src/js/service/UnitCountMachine.js
> +  }
세상에.. 오랜만에 살펴보니 왜 저도 ui영역이 아닌데 여기서 redraw를 썼을까? 고민했었는데
휴먼 에러였습니다. withdraw로 고치도록 할게요!

2022-12-29 08:28 UTC, crontable commented on src/js/service/ProductManager.js
> +  }
네이밍이라고 하는 것이 정말 중요하다는 것을 체감합니다.
각기 정해진 어휘의 뜻이 있을지라도 하나의 어휘에 다양한 뜻이 내포되어 있고 두 단어가 합성된 경우에는 또 사람마다 정의되는 뜻이 달라진다고 생각합니다.
그래서 팀에서 작업하게 된다면 명확한 기준과 정의가 있어야 하고 이를 정의하기 위한 구체적인 소통 수단이 필요하다고 생각해요!
  
  제가 정의한 상품관리자라고 하는 것은 누군가 자판기를 관리하는 사람을 지칭하는 것이 아니라 상품을 관리하는 모듈로서 정의내려봤어요! -er이 붙어 사람을 지칭하는 듯해 이 부분이 조금 걸렸지만, 무언가 역할을 수행해 주는 역할을 표현하기 위해서는 해당 단어가 충분하다고 생각했기 때문이에요.

  실제로 ‘CookieManager(Java)’, ‘PackageManager(Android)’로도 네이밍이 지어지고 있습니다. 물론, 자판기는 현실 세계의 물건을 표현하는 부분이어서 준일님께서 제안해 주신 “사람“이 관리하는 것으로 오해할 소지가 있다고 생각은 되지만, 그것이 꼭 사람으로서만 해석될 여지는 없을 것이라고 생각해요. 클린 코드 자바스크립트가 미션 수행을 위해서 현실 세계의 흔한 도메인인 `자판기` 소재를 가져왔지만, 실제 프로젝트를 진행하면서 -er의 뜻이 내포한 '사람'이라는 의미가 혼란을 초래할 여지는 많이 없을 것임을 고려하여 네이밍하기도 했어요!

저도 처음에 설계할 때는 위의 구조로 설계를 해볼까 고민했지만,
클래스 이름에서 표현하는 것은 VendingProduct(+s)로 복수의 의미만을 전달하고 있어 복수의 상품을 표현하는 것만으로는 아래의 기능까지 내포하고 있다고 어렵다고 판단했습니다.
- 상품의 이름을 검증한다(공백이 있으면 안 된다)
- 상품의 가격을 검증한다
- 상품의 수량을 검증한다
- 해당 상품 분류에 재고를 더한다
- 해당 상품을 꺼낸다 (~~draw~~ withdraw)

2022-12-29 08:43 UTC, crontable commented on src/js/service/ProductManager.js
> +export default class ProductManager {
[아래의 답변](https://github.com/next-step/js-vending-machine/pull/56#discussion_r1058809928)으로 갈음하겠습니다

2022-12-29 08:47 UTC, crontable commented on src/js/util/object.js
> +      }
휴먼 에러 찾아주셔서 감사해요!

2022-12-29 10:40 UTC, crontable commented on src/js/component/styled-button.js
> +<button class="btn btn-secondary"><slot></slot></button>
어떤 스타일을 정의하라는 말씀이신지 이해를 하지 못했습니다.
조금 더 구체적인 설명 부탁드릴 수 있을까요?

2022-12-30 05:52 UTC, JunilHwang commented on src/js/service/VendingMachine.js
> +  #insertedMoney;
현재에도 `VENDING_MACHINE_CONSTANT.PURCHASABLE_MONEY.MIN_AMOUNT = 100`; 처럼 수정이 가능해서요.
그렇다면 말씀해주신 것 처럼 분리한게 의미가 있을까요?

2022-12-30 05:53 UTC, JunilHwang commented on src/js/service/VendingMachine.js
>    }
생성하는 시점에 방어를 해야하지 않을까요?

2022-12-30 05:58 UTC, JunilHwang commented on src/js/service/VendingMachine.js
> +  }
`vendingMachine.returnChanges()`를 한글로 변환해보자면,  `자판기.변경_사항_반환()` 인데, 거스름돈과 관련있다고 생각되지 않아서요!

2022-12-30 05:58 UTC, JunilHwang commented on src/js/service/ProductManager.js
> +  }
그렇다면
- 상품의 이름을 검증한다(공백이 있으면 안 된다)
- 상품의 가격을 검증한다
- 상품의 수량을 검증한다
이 정도만 VendingProduct로 분리할 수 있지 않을까 싶어요 ㅎㅎ

호중님 말씀처럼 ProductManager가 적합한 네이밍이라고 하더라도, 그 내부에서 하는 일은 적합하지 않다고 생각합니다.

2022-12-30 06:00 UTC, JunilHwang commented on src/js/service/VendingMachine.js
> +  }
vendingMachine.returnChanges()를 한글로 변환해보자면, 자판기.변경_사항_반환() 인데, 거스름돈과 관련있다고 생각되지 않아서요!

2023-01-02 07:39 UTC, crontable commented on src/js/service/ProductManager.js
> +  }
[위에서](https://github.com/next-step/js-vending-machine/pull/56#discussion_r1057709947)
- 자판기(VendingMachine클래스) - 자판기 상품들(VendingProducts 클래스) - 자판기 상품(VendingProduct클래스)의 구조로 이해했었는데요!
VendingProducts는 클래스로 만드는 것이 아니라 배열로써 상태관리를 하라고 말씀을 해주신 부분일까요?
`class를 하나 더 만들고,`라고 말씀해 주셔서 위의 구조 모두 클래스로 보았어요!

아니면,
- VendingMachine (클래스) - VendingProduct (클래스)
위의 구조로 만들되 VendingMachine에서 VendingProduct의 인스턴스를 배열로서 상태를 가지고 있는 것으로 설계하고 아래처럼 기능을 포함하도록 하라고 말씀하시는 것일까요?

- VendingMachine
    - 해당 상품의 분류에 재고 더하는 함수, 빼는 함수
- VendingProduct
    - 상품의 이름,가격,수량 검증하는 메서드

2023-01-02 07:56 UTC, crontable commented on src/js/service/VendingMachine.js
> +  #insertedMoney;
freeze 코드를 누락했군요. 보완하겠습니다!

2023-01-02 08:02 UTC, crontable commented on src/js/service/VendingMachine.js
>    }
(ProductManager는 피드백 주신 대로 수정할 예정이니 UnitCountMachine으로 설명해드릴게요!)

생성하는 시점이라고 하는 것이 VendingMachine 클래스의 생성자에서의 시점을 말씀하시는 걸까요?
VendingMachine 클래스에서 UnitCountInfo가 잘 들어왔는지를 VendingMachine 생성사자에서도 검증할 수도 있겠지만, 검증하는 것 자체의 역할은 UnitCountInfo에서 진행하는 것이 보다 타당하지 않을까요?

이 부분과 관련해서 어떤 생성자에서 방어를 해야 하는 것이 바람직한지 두 가지의 관점 중 하나가 틀린 것으로 봐야 할까요? 아니면, VendingMachine 클래스의 생성자에서 유효성 검증을 방어하는 것이 좀 더 타당하다고 말씀해주시는 걸까요?
둘 중 어떠한 카테고리에 속하는지 리뷰어님의 구체적인 말씀을 들어보고 싶어요!

리뷰어님의 의견에 근거하여 맞다면 저도 올바른 방향으로 수정하는 것이 타당하고 나중에 제가 비슷한 케이스를 만났을 때 리뷰어님이 제시해주신 방향대로 작성한다면, 이에 대한 근거를 제시할 수 있을 것 같습니다.

2023-01-02 08:05 UTC, crontable commented on src/js/service/VendingMachine.js
> +  }
저는 변경사항을 반환한다는 것이 아니라` returnChanges() -> 자판기.잔돈_반환()` 으로 보았던 입장입니다.
미국인이나 영국인 혹은 영어권에서 returnChange(s)라고 하면 어색한 부분이 있을까요?
혹시 changes <-- 불가산명사인데 복수형으로 붙여서 그렇게 말씀해주셨던 걸까요?

<img width="556" alt="image" src="https://user-images.githubusercontent.com/22428471/210206531-2e219b1f-7070-4b9e-927d-fb50327737fd.png">


<img width="1289" alt="image" src="https://user-images.githubusercontent.com/22428471/210207050-8b345898-6b00-4bfd-80b6-32826b4c994a.png">

2023-01-02 08:24 UTC, crontable commented on src/js/ui/constant.js
> +};
> 상수의 경우 재활용이 목적이 아닌 "의미 부여"가 목적이다

이전에 리뷰어님께서 제게 피드백주신 말씀에 울림이 있어서 항상 상수로서 의미를 부여하고 있었습니다.
이 부분도 사실 1회 생성 후 사용될 일이 없기는 하지만, 의미를 부여하는 것이 맞겠다는 생각이 들어서 작성했던 부분이었어요.
이전에 피드백주셨던 부분과는 문맥이 다소 차이는 있겠지만, 어떤 부분에 포커스를 두고 코드를 작성해야 하는지 감이 잘 오지 않네요 ㅠㅠ

제가 틀리게 작성했다거나 성능 상의 이슈가 되거나, 혹은 리뷰어님께서 보다 타당한 방법을 제시해 주신 부분인지 궁금합니다!

2023-01-02 08:25 UTC, crontable commented on src/js/util/dataSaver.js
> +}
위의 내용에 추가적인 피드백을 받으면 다른 디렉터리로 분류 후 피드백까지 반영하겠습니다!

2023-01-02 08:26 UTC, crontable commented on src/js/util/object.js
> +}
해당 부분은 좀 더 바람직한 방법을 찾았습니다.
객체 깊은 복사 -> 객체 깊은 Freezing -> 반환 

상수를 freezing해야 하기 때문에 freezing하는 과정은 별개로 분리하는 것이 타당하다는 판단이 들었습니다.
보완해서 리뷰 요청드릴게요!

2023-01-02 08:28 UTC, crontable commented on src/js/util/object.js
> +}
해당 부분은 좀 더 바람직한 방법을 찾았습니다.
(이전에 제가 제시해 드렸던 방향이 아니라 리뷰어님께서 제시해 주신 방향으로 수정해볼 수 있게 되었습니다)
객체 깊은 복사 -> 객체 깊은 Freezing -> 반환

상수를 freezing해야 하기 때문에 freezing하는 과정은 별개로 분리하는 것이 타당하다는 판단이 들었습니다.
보완해서 리뷰 요청드릴게요!

2023-01-02 12:39 UTC, JunilHwang commented on src/js/service/ProductManager.js
> +  }
- 제가 의도한건 전자가 맞습니다.
- VendingProducts는 [일급 컬렉션](https://jojoldu.tistory.com/412)을 생각하고 이야기 했었답니다!
- 그런데 호중님이 ProductManager로 유지하길 원하셔서 다시 고민을 해봤는데, ProductManager 라는 것 자체가 사실 VendingProduct(자판기)의 역할에 더 적합한게 아닐까 라는 생각이 들었답니다!

2023-01-02 12:44 UTC, JunilHwang commented on src/js/component/styled-button.js
> +<button class="btn btn-secondary"><slot></slot></button>
css file의 import 없이
style-button component만 사용해도 그려져야 더 명확한 의미의 컴포넌트가 되는게 아닐까요?

2023-01-02 12:47 UTC, JunilHwang commented on src/js/service/VendingMachine.js
>    }
@sannimdev 
저는 검증을 해야 한다면, 양쪽에서 모두 검증이 필요하다고 생각합니다.
unitCountInfo를 멤버변수로 사용하는데, 
unitCountInfo가 어떤 성격을 가지고 있는지 VendingMachine에서 보장해야 하지 않을까요?

쉽게 말해서 지금은 VendingMachine의 안정성을 사용하는 측에 떠넘기는 형태입니다.
VendingMachine이라는 것의 완성도는 VendingMachine 자체에서 신경써야 하지 않을까요?

2023-01-02 12:49 UTC, JunilHwang commented on src/js/service/VendingMachine.js
> +  }
<img width="1316" alt="image" src="https://user-images.githubusercontent.com/18749057/210233523-da027883-40d3-446c-87d5-34491b24ce51.png">
<img width="1339" alt="image" src="https://user-images.githubusercontent.com/18749057/210233537-ed3621e2-cab4-4909-a31b-9e54d3cdb8ad.png">
전혀 다른 의미가 되어버리네요..!

2023-01-02 12:50 UTC, JunilHwang commented on src/js/ui/constant.js
> +};
instance 자체에 의미를 내포할 수 있다고 생각했어요!
이럴 경우 인스턴스 내부에서만 상수를 쓰게 되고 외부에서는 쓸 필요가 없는거죠.
- 외부에서 상수를 통해 데이터에 접근하는게 좋을지
- 인스턴스(객체) 내부에게 아예 위임하는게 좋을지
무엇이 더 적합하다고 생각하시나요?

2023-01-02 12:53 UTC, JunilHwang commented on src/js/util/object.js
> +}
위에랑 중복된 피드백이였네요 ㅠㅠ

2023-01-03 04:10 UTC, crontable commented on src/js/ui/constant.js
> +};
정리하자면, 상수로 정의하여 사용하느냐 마느냐의 문제라기보다는 instance에 역할과 책임을 부여하면 상수를 굳이 정의할 필요가 없다는 쪽이 맞겠죠?

그 근거로는 아래와 같이 외부에서 상수를 통해 데이터를 접근하지 말고

```js
// - src/js/index.js

setClickEventListenerWithVendingMachine(querySelector(SELECTOR_MAP.BUTTON.PRODUCT_ADD), (vendingMachine) => {
  // (중략)

///////////////////////////////////////////////////
  saveItem(DATA_STORAGE.PRODUCTS, vendingMachine.productManager.products);
/////////////////////////////////////////////////////
});
```

다음과 같이 인스턴스에 위임하여 별도로 작성을 권장
```js
// ProductStorage 클래스의 메서드

saveProduct(product) {
    localStorage.setItem(key항목명, 상품명); // ...
}
```

그래서 `setClickEventListenerWithVendingMachine` 함수에서는 ProductStorage.saveProduct 메서드를 통해 상품 항목을 전달하고 해당 ProductStorage의 인스턴스에게 로컬스토리지에 저장하는 역할과 책임을 부여하는 쪽으로 작성하라고 말씀하시는 부분일까요? 

그런 것 같아서 일단 이대로 진행해볼게요!

2023-01-03 04:16 UTC, crontable commented on src/js/service/ProductManager.js
> +  }
아아! `일급 컬렉션을 사용한다고 말씀하신 부분이었다면` 그 부분에 동의합니다! 
의도하신 부분으로 수정해보겠습니다

2023-01-03 04:17 UTC, JunilHwang commented on src/js/ui/constant.js
> +};
@sannimdev 
네 맞습니다!

2023-01-05 11:54 UTC, crontable commented on src/js/service/VendingMachine.js
> +  }
change가 불가산명사일 때 잔돈이라는 의미를 나타내는 것으로 파악되어 changes => change로 변경할게요!
파파고를 기준으로는 changes라고 입력하여도 잔돈을 돌려준다고 의미를 해석해 주고 있기 때문에 이 부분은 이름을 고민하면서 여러 번역기를 돌려봐야겠네요! 

<img width="1298" alt="image" src="https://user-images.githubusercontent.com/22428471/210774581-f3d62a67-1e04-48ff-9ac1-e21a31a2dd52.png">

2023-01-05 14:49 UTC, JunilHwang commented on src/js/ui/DataStorage.js
> +  }
인자로 받아오는 key는 제거해도 되지 않을까요!?
```js
  saveItem(data) {
    localStorage.setItem(this.key, JSON.stringify(data));
  }
```

다른 부분도 동일합니다!

2023-01-05 14:49 UTC, JunilHwang commented on src/js/ui/DataStorage.js
> +  }
```js
  #key;

  /**
   *
   * @param {string} key
   */
  constructor(key) {
    this.#key = key;
  }
```

key를 public하게 관리할 필요는 없을 것 같아요!

2023-01-07 01:02 UTC, crontable commented on src/js/ui/DataStorage.js
> +  }
휴먼에러 수정할게요 ㅠㅠ

2023-01-07 01:02 UTC, crontable commented on src/js/ui/DataStorage.js
> +  }
여기도 휴먼에러..

2023-01-13 12:32 UTC, crontable commented on index.html
> +          ></smart-table>
물리적 시간 제약 이슈로 이 부분과 관련된 적용 코드는 삭제하였습니다.

2023-01-13 12:41 UTC, sannimdev commented on index.html
> +    <script type="module" src="./src/js/component/smart-table.js"></script>
요건 `import from 경로`를 의도하신 것 같습니다. Webpack 설정을 하지 않고 프로젝트를 진행한 것이라서 양해를 구합니다. (작동하지 않습니다 ㅠ)

2023-01-13 12:48 UTC, crontable commented on src/js/component/smart-table.js
> +    this._shadowRoot.appendChild(template.content.cloneNode(true));
```html
<smart-table title="h2에 들어갈 제목" />
```

위에서 지정한 "title"의 속성값은 Web Component의 사이클인 `attributeChangedCallback`을 활용하고자 하는 의도였습니다.
리뷰어님께서 제안해 주신 대로 생성자에서 호출되었을 때 바로 적용하는 방법으로 지정해 보았는데
생성자에서 바로 지정해주는 방법과, 라이프사이클인 `attributeChangedCallback` 메서드에서 대응하는 것과의 차이점에 관해서 어떻게 생각하시는지 의견을 알고 싶습니다!

2023-01-13 12:48 UTC, sannimdev commented on src/js/component/styled-button.js
> +<button class="btn btn-secondary"><slot></slot></button>
styled-button 이슈는 시간제약상 이번 미션에서 제외하기로 하였습니다. 양해 부탁드려요

2023-01-13 13:21 UTC, sannimdev commented on src/js/service/VendingMachine.js
>    }
@JunilHwang 

> unitCountInfo를 멤버변수로 사용하는데,
> unitCountInfo가 어떤 성격을 가지고 있는지 VendingMachine에서 보장해야 하지 않을까요?

현재 코드: 

UnitCountInfo를 정의하면, UnitCountInfo의 데이터 형식은 어떻게 이루어져 있는지 아래와 같이 검증하는 작업을 UnitCountInfo의 `#isValidUnitCountInfo`의 private 메서드를 통해 확인하고 있습니다.

```json
{
   amount: 숫자,
   unnitInfo: {10: 숫자, 50: 숫자, 100: 숫자, 500: 숫자}
}
{"amount":2260,"unitInfo":{"10":1,"50":1,"100":2,"500":4}}
```

제가 이해한 준일님 제안:

UnitCountInfo의 데이터 형식은 어떻게 이루어져 있는지 아래와 같이 검증하는 작업인 `#isValidUnitCountInfo` 메서드의 내용은
UnitCountInfo가 아니라 VendingMachine에 작업이 작성되어 있어야 하고 VendingMachine 생성 시 unitCountInfo로 들어온 값을 그때 검증해야 한다.

이것이 맞을까요?

그런데 저는, VendingMachine 내부에 속한 UnitCountInfo라고 하는 이 개념 자체가 VendingMachine에서 빠지고 무언가 새로운 구조로 새로운 개념으로 대체될 때, UnitCountInfo 내용만 제거하고 새로운 개념으로 대체하면 된다고 생각했거든요. 

제가 이해한 것이 맞다면, 저는 VendingMachine에서 생성자 인수로 unitCountInfo로 받은 것이 UnitCountInfo 형식이 맞는지 검증하는 작업이 VendingMachine에 작성되는 것에 아직 공감하기 어렵습니다. 보다 구체적이거나 제가 참고할 만한 부분이나 서적을 추천해주실 수 있을까요?

2023-01-14 01:57 UTC, JunilHwang commented on src/js/component/smart-table.js
> +    this._shadowRoot.appendChild(template.content.cloneNode(true));
값을 어느 시점부터 들고 있는지의 차이가 아닐까요!?

2023-01-14 02:00 UTC, JunilHwang commented on src/js/service/VendingMachine.js
>    }
중요한건 `UnitCountInfo` 내부의 값을 검증하는 것이 아닌
`UnitCountInfo`인지 검증하는 것입니다.

> VendingMachine 내부에 속한 UnitCountInfo라고 하는 이 개념 자체가 VendingMachine에서 빠지고 무언가 새로운 구조로 새로운 개념으로 대체될 때, UnitCountInfo 내용만 제거하고 새로운 개념으로 대체하면 된다고 생각했거든요.

그렇다면 이에 대한 인터페이스? 라도 정의가 되어야 하는게 아닐까요?
UnitCountInfo에 다른게 들어올 수 있다면
어떤 형태의 것들이 들어오는지 최소한의 정의가 필요하다고 생각해요!
지금은 아무 조치도 취해놓지 않은 상태이기 때문에 불확실한 코드가 되어버린답니다 ㅠㅠ

검증이 어려운게 아니라

```js
if (unitCountInfo instanceof UnitCountInfo) { /** 조치 **/ }
```
처럼만 해도 된답니다!

가령 컴퓨터로 따지자면

usb라는 interface가 있고
이 usb를 꽂는 곳에는 usb의 형태만 갖춰져있다면 무엇을 꽂아도 되는 것 처럼요!

2023-01-14 02:29 UTC, JunilHwang approved these changes
안녕하세요 호중님!
자판기 미션은 여기서 마무리하도록 하겠습니다 ㅎㅎ
질문주신 내용들에 대해서 답변 달아놓았으니 한 번 확인 부탁드려요!
이 외에도 고민해볼 부분들에 대해 코멘트 남겨놨습니다.

긴 시간 동안 건설적인 피드백 주고 받을 수 있어서 즐거웠습니다!
2023년이 마무리 되었을 때의 호중님의 모습이 무척 기대되네요 😄

부디 저의 피드백이 호중님에게 도움이 되었길 바랍니다 🙏
감사합니다!

2023-01-14 02:29 UTC, JunilHwang commented on src/js/component/smart-table.js
> +    this._shadowRoot.appendChild(template.content.cloneNode(true));
값을 어느 시점부터 들고 있는지의 차이가 아닐까요!?
지금은 h2가 비어있는데,
이걸 처음부터 채워진 상태로 가지고 있어야 렌더링 될 때 자연스러울 것 같아서요!

2023-01-14 02:29 UTC, JunilHwang commented on src/js/service/VendingMachine.js
> +    this.#unitCountMachine = new UnitCountMachine(unitCountInfo);
이렇게 아예 내부에서 UnitCountMachine로 감싸는 것도 좋은 방법인 것 같네요!

다만, 객체지향에는 [다형성](https://steady-coding.tistory.com/446) 이라는 개념이 있습니다.

```js
new VendingMachine(products, unitCountInfo);
new VendingMachine(new Products(products), unitCountInfo);
new VendingMachine(products, new UnitCountMachine(unitCountInfo));
new VendingMachine(new Products(products), new UnitCountMachine(unitCountInfo));
```
어떤 느낌인지 감이 오시나요?
위의 네 가지 케이스가 모두 정상적으로 동작하게 하려면 어떻게 해야 좋을까요?

2023-01-14 02:29 UTC, JunilHwang commented on src/js/service/VendingMachine.js
>    }
가령 `Products`라는 일급컬렉션을 만들어서 관리한다면, 여기에 대한 로직도 위임할 수 있겠죠!?

2023-01-14 02:29 UTC, JunilHwang commented on src/js/service/Product.js
> +export default class Product {
Product라는 이름은 너무 범용적인 것 같아요!

2023-01-14 02:29 UTC, JunilHwang commented on src/js/service/VendingMachine.js
> +    return isInteger(id) ? products.find((p) => p.id === id) : products.find(({ name: n }) => n === name);
```js
    return products.find((p) => isInteger(id) ? p.id === id : p.name === name);
```
이렇게 표현할 수도 있을 것 같아요!

다만 지금 쓰임새로 봐선
```js
    return products.find((p) => p.id === id || p.name === name);
```
이렇게 표현해도 무방할 것 같아요~

2023-01-14 02:29 UTC, JunilHwang commented on src/js/service/VendingMachine.js
> +  }
```js
  withdraw(id) {
    const product = this.#find({ id });
    if (!product || product.isEmpty()) return null;
    return product.pick(); // 내부적으로 amount 감소 후 필요한 데이터만 뽑아서 반환
```
product 내부 변수에 직접 접근하는게 아니라, 이렇게 message(method)를 보내야 더 명확하게 product의 역할을 수행할 수 있는게 아닐까요?

2023-01-14 02:29 UTC, JunilHwang commented on src/js/service/VendingMachine.js
> +  }
이렇게 보낼 때도 고민해볼 부분은
"필요한 데이터만 뽑아서 반환할 수 있는지" 입니다!

2023-01-14 02:29 UTC, JunilHwang commented on src/js/service/VendingMachine.js
> +    console.log(product, id);
콘솔은 제거해주세요!

2023-01-14 02:29 UTC, JunilHwang commented on src/js/service/VendingMachine.js
>      }
여기서도 product 내부의 멤버변수에 꼭 접근이 필요한지,
아니면 어떻게 product에 메세지를 보내서 관계를 맺을지 고민해보시면 좋을 것 같아요!

2023-01-14 02:29 UTC, JunilHwang commented on src/js/service/VendingMachine.js
> +  };
insertMoney라는 것 자체를 검증하고 있는데,
잘 생각해보면 이 부분도 하나의 객체로 관리할 수 있지 않을까요?

값에 대한 검증로직이 있다 => 객체로 추출할 수도 있다.

이런 흐름으로 보시면 좋을 것 같아요!

지금 "자판기"라는 도메인을 토대로 미션을 진행 중인데
"자판기"라는 개념 자체를 추상화하고
"음료수 자판기"도 있고,
"커피 자판기"도 있고,
"과자 자판기"도 있고

굉장히 다양한 종류의 자판기를 만들 수 있으며
이 때 추상화해서 뽑아낼 수 있는 자판기의 개념이 무엇인지 고민후에 그걸 인터페이스로 만들어서 관리한다고 생각해보세요!
그럼 이 때 정말 모든 자판기에서도 사용할 수 있는 로직이 있는데
그걸 하나의 "객체"로서 관리한다면 어떨까요?

그 중 하나가 "돈"이 될 수 있을 것 같아요.

- 최소 금액이 있고
- 잔돈이 있고
- 삽입 금액을 비교해야 하고
- ...

이런 느낌으로여 ㅎㅎ

2023-01-14 02:29 UTC, JunilHwang commented on src/js/ui/DataStorage.js
> +export default class DataStorage {
이게 ui쪽에 있는게 맞을까요?

2023-01-14 02:29 UTC, JunilHwang commented on src/js/service/VendingMachine.js
> +export const vendingMachine = new VendingMachine(savedProducts, savedUnitCounts);
이 코드(VendingMachine)만 nodejs 같은 다른 런타임에서 실행한다고 치면,
여기서 오류가 발생할 수 있겠네요!

2023-01-14 02:29 UTC, JunilHwang commented on src/js/ui/DataStorage.js
> +  }
```suggestion
  #key; #storage;

  /**
   *
   * @param {string} key
   */
  constructor(key, storage = localStorage) {
    this.#key = key;
    this.#storage = storage;
  }

  /**
   *
   * @param {Object|Object[]} data
   */
  saveItem(data) {
    this.#storage.setItem(this.#key, JSON.stringify(data));
  }

  loadItem() {
    const stringified = this.#storage.getItem(this.#key);
    return stringified ? JSON.parse(stringified) : null;
  }
```
이런식으로 사용한다면 storage에 localStorage가 올 수도 있고, sessionStorage가 올 수도 있고, 혹은 내가 직접 만든 storage가 올 수도 있겠죠!?

2023-01-14 02:29 UTC, merged